Cargo.lock, zilliqa/Cargo.toml, zilliqa/src/state.rs
Use the re-exported version from `sha3` instead to avoid problems with mismatching dependency versions.
=> Remove dependency on generic-array

zilliqa/src/api/erigon.rs, zilliqa/src/api/eth.rs, zilliqa/src/api/ots.rs, zilliqa/src/api/types/eth.rs, zilliqa/src/api/types/mod.rs, zilliqa/src/api/types/ots.rs, zilliqa/src/api/types/zilliqa.rs, zilliqa/src/api/zilliqa.rs
I did quite a bit of moving around of the existing Ethereum API types, to make it clearer what was specific to the Ethereum/Zilliqa APIs. This might cause some noise in the diff, I'm happy to split this up if it causes issues with reviews.
=> Implement Zilliqa `GetLatestTxBlock` API

zilliqa/src/api/eth.rs, zilliqa/src/api/ots.rs, zilliqa/src/api/types/eth.rs, zilliqa/src/consensus.rs, zilliqa/src/exec.rs, zilliqa/src/message.rs, zilliqa/src/node.rs
No longer rely on the TX trace, but do use it for ots_getInternalOperations (which has a corresponding test enabled in integration tests). I realised also that eth_call did not respect value which was causing the ots test to fail.
=> Revert state accounts reflecting evm balances

zilliqa/tests/it/main.rs
Provides a better error requiring Solc version 0.8.20 running on the host system
=> FIX: Solc Shanghai Version check

.github/workflows/ci.yaml
They are larger, so the test suite runs quicker.
We are already running these machines for ZQ1, so using them here is basically free. :)
=> Use self-hosted runners for CI integration tests 

z2/src/setup.rs
With the consensus improvements, z2 could not restart from persistence as it gets a new set of private keys each time. This is one way to get around that (the other would be saving the private keys to disk which seems messier).
=> start z2 deterministically

.github/workflows/ci.yaml
This reverts commit df7d0e013488099db70a748a24cc6dd45dccbb11.
=> Revert "Use self-hosted runners for CI integration tests (#501)"

Cargo.lock, scripts/js_test.sh, z2/src/setup.rs
Update js tests to new and improved from Z1. 
There is some issue when running against a network (a race on tx receipts) so run against a single node for now.
=> update js tests

zilliqa/src/message.rs, zilliqa/src/node.rs, zilliqa/src/node_launcher.rs, zilliqa/src/p2p_node.rs, zilliqa/tests/it/main.rs, zilliqa/tests/it/persistence.rs
Separates the `InternalMessage` and `ExternalMessage` structs to be sent through different channels, and removes the combined Message enum.
The purpose of this is to improve the type safety of sending messages around. `InternalMessage` is intended for messages within the same running process - from a shard thread to the p2p coordinator process, or (in the future) between shard threads for cross-shard messaging. `ExternalMessage` meanwhile is the type for actual p2p messages which are sent over the network.
Without this PR, both types go through the same tokio `channel`s, and all channels accept a common `Message` type that encapsulates both of the above. This means that while we can handle messages in a type-safe manner with pattern matching, the actual communication channel does not …
=> Split message channels

.github/workflows/ci.yaml
We're replacing the AWS-hosted runners with ones in GCP. On AWS, we saw spurious and unexplained SIGKILLs - I started 12 jobs on the GCP runners and didn't see the SIGKILL, so the issue might be fixed here.
=> Use GCP-hosted runners for CI tests

zilliqa/tests/it/main.rs
The comment should make it clear, but as I noted in my main forking PR, the index has to be recalculated otherwise it incorrectly appears as if the messages are all or mostly going to node 0.
=> fix span messages in tests

zilliqa/src/block_store.rs
At certain points, it becomes apparent to the node it is lagging (proposal received with a parent hash it does not know of). At this point, it triggers a request for blocks. If the proposal it recieved was far ahead of its own head, this can cause wasted compute (and wasted time in test framework) as it immediately discards the response due to it being 'loose'.
to avoid this, make sure the block you are asking for is not higher than your head.
=> Avoid requesting blocks we won't accept anyway

zilliqa-macros/src/test.rs, zilliqa/src/message.rs, zilliqa/src/time.rs, zilliqa/tests/it/main.rs
This means each test instance gets its own independent and deterministic value of fake time.
=> Use task-local values for fake time

zilliqa/src/message.rs, zilliqa/src/time.rs
Not sure that this is the clean way to solve the issue, but essentially, 
message.rs:
```
fn systemtime_strftime(timestamp: SystemTime) -> Result<String> {
let time_since_epoch = timestamp.elapsed()?;
```
...
```
pub fn elapsed(&self) -> Result<Duration, SystemTimeError> {
self.duration_since(SystemTime::now())
}
```
If the block timestamp is before now, then it will panic, because it can't be a duration since a time in the future. I think it should be time since epoch.
I am not even sure how this can happen in the tests - it suggests to me that something isn't right with the fake time?
=> Fix potential panic when printing time

zilliqa/src/api/eth.rs, zilliqa/src/api/ots.rs, zilliqa/src/api/zil.rs, zilliqa/src/consensus.rs, zilliqa/src/evm_backend.rs, zilliqa/src/exec.rs, zilliqa/src/state.rs, zilliqa/src/transaction.rs, zilliqa/tests/it/consensus.rs, zilliqa/tests/it/main.rs
Instead of defining `Address` as a newtype of `Address(H160)`, we instead just alias `Address = H160`. This simplifies quite a bit of code and I'd argue it doesn't cost us any type safety, because we aren't using `H160` for anything other than addresses. The only thing this might make more difficult in the future is changing the width of addresses, but I'd argue that will be difficult anyway and its not worth paying the complexity cost now.
=> Simplify address type

zilliqa/src/api/eth.rs, zilliqa/src/consensus.rs, zilliqa/src/exec.rs, zilliqa/src/transaction.rs, zilliqa/tests/it/contracts/RevertMe.sol, zilliqa/tests/it/eth.rs
One thing I'm not sure about is whether event logs should be kept on revert - I haven't checked what Eth clients do, and I'm not sure what ZQ1 does either in these cases. So I haven't touched them here, keeping the previous behaviour of keeping them available.
=> Add gas charging on revert, and gas_used tracking to receipts. Add tests for reverted transactions.

zilliqa/src/bin/zilliqa.rs, zilliqa/tests/it/eth.rs
`tracing_subscriber::fmt::init();` and `tracing_subscriber::fmt().init();` do not behave the same - the first will respect RUST_LOG and the second will not
=> make subscriber respect RUST_LOG

zilliqa/src/db.rs, zilliqa/src/node.rs, zilliqa/tests/it/main.rs
The test `consensus::network_can_die_restart` had a race condition where when it kills the nodes, their DBs are in a state of writing. This caused it to sometimes randomly fail. This forcibly flushes them so that the tests are deterministic and pass once again.
=> Flush db to disk before copying it over in test

zilliqa-macros/src/test.rs
example `ZQ_TEST_SEED_SPANS=1 RUST_LOG=zilliqa=trace,it=trace cargo test  --release --test it -- consensus::launch_shard`
Produces:
```
2023-12-05T20:01:53.776561Z TRACE {seed=16741818491380055426}:handle_message{index=12}: zilliqa::consensus: head block request: highest block number: 4
2023-12-05T20:01:53.776567Z TRACE {seed=16741818491380055426}:handle_message{index=12}: zilliqa::consensus: handling block proposal de38f21300ab3f2d97787efabdc41468c08840b035d2a8362df0d59c6a87fb36 block_view=5 block_number=5
2023-12-05T20:01:53.777132Z TRACE {seed=16741818491380055426}:handle_message{index=12}: zilliqa::consensus: (check block) I think the block proposer is: 12D3KooWKnS5uGQ1X3KAp95PA65CtEvkNdTWVBtrxrwLhhJUtFYr, we are 12D3KooWDp2EZLhPeH58WebRCFkd8mN5EGFsH1SU2jrtv3zyMG77
```
Useful to turn …
=> allow seed in spans

zilliqa/src/cfg.rs, zilliqa/src/consensus.rs, zilliqa/src/lib.rs, zilliqa/src/node.rs, zilliqa/src/pool.rs, zilliqa/src/transaction.rs, zilliqa/tests/it/eth.rs
The mempool now lives in its own `TransactionPool` data structure. I have changed the details of the pool's implementation, but I think the high-level logic should remain the same:
* Return only valid transactions (which have a nonce equal to the sender's nonce)
* Of these, prioritise transactions with a higher gas price.
The comments in `pool.rs` should hopefully do a reasonable job at explaining the new logic and how it is implemented.
=> Refactor transaction pool into separate data structure

zilliqa/src/api/ots.rs, zilliqa/src/consensus.rs, zilliqa/src/db.rs, zilliqa/src/exec.rs, zilliqa/src/node.rs
It currently doesn't work. We will need to re-add something similar to support Otterscan (tracked in our roadmap). I figured it was counterproductive to leave non-working code in the repository and I'd rather recover anything useful when we implement this properly later.
=> Remove touched address index

.github/workflows/ci.yaml, zilliqa/src/api/ots.rs, zilliqa/src/exec.rs, zilliqa/src/node.rs, zilliqa/src/pool.rs, zilliqa/src/state.rs, zilliqa/tests/it/main.rs
This ensures the nightly-only options in our `rustfmt.toml` are respected.
This commit also fixes the new Clippy lints introduced by the current nightly version.
=> Run CI with nightly Rust compiler

Cargo.lock, zilliqa/Cargo.toml, zilliqa/build.rs, zilliqa/src/api/zil.rs
It now returns an object containing `Commit` and `Version` fields, which is what ZQ1 does.
`Commit` is populated by the full SHA of the git commit at which the node was built.
`Version` is populated by a git tag, if one exists or an abbreviated commit SHA if not. If the working directory is dirty, `-dirty` is appended to the version. This is close to the output of `git describe --always --dirty --tags`.
Example output when `HEAD` is tagged:
```
{
"Commit": "c2ecdc27e588a0ababcbe9a00567351d739664b4",
"Version": "foobar"
}
```
Example output when `HEAD` is not tagged:
```
{
"Commit": "c2ecdc27e588a0ababcbe9a00567351d739664b4",
"Version": "c2ecdc2"
}
```
=> Fix response format of `GetVersion`

.dockerignore, Dockerfile
1. We need to un-ignore the `.git` directory when copying files into the build container, so `vergen` can read git information.
2. Previously we copied everything into `/`. It appears `vergen` or `git2` doesn't like Git repositories named `/`, so instead we copy and build everything into `/zilliqa`.
=> Fix local docker builds

zilliqa/src/api/zil.rs
The CreateTransaction method allows sending code and data field as `null`, so we make it optional and provide default implementation if they are received as `null`.
=> Allow null in code and data field in CreateTransaction

README.md, zilliqa/src/api/eth.rs
These were implemented a while ago, but we forgot to update the supported APIs list.
=> Update README with `eth_getUncle*` implementation status

.github/workflows/ci.yaml
Avoids the risk of having CI run for 10-15 minutes only to then fail on a rustfmt mismatch.
Assuming there isn't any deeper reason for why it was put after `cargo test` in the first place?
=> CI: run rust fmt before kicking off the test suite, for fail-early behaviour

zilliqa/src/api/erigon.rs, zilliqa/src/api/eth.rs, zilliqa/src/api/mod.rs, zilliqa/src/api/ots.rs, zilliqa/src/api/subscription_id_provider.rs, zilliqa/src/api/types/eth.rs, zilliqa/src/consensus.rs, zilliqa/src/node.rs, zilliqa/src/node_launcher.rs, zilliqa/tests/it/eth.rs, zilliqa/tests/it/main.rs
This adds the `eth_subscribe` and `eth_unsubscribe` APIs for the Ethereum pub-sub protocol.
Currently, only `newHeads` are supported (`logs` and `newPendingTransactions` are also specified). The API only works over a websocket, because they need a duplex connection.
The implementation works by adding a `broadcast::Sender` to `Consensus` which publishes `BlockHeader`s whenvever they are produced. When a client makes a new subscription, it subscribes to this sender. The sender keeps a buffer of the 4 latest blocks in memory. If any reciever falls behind these 4 blocks (because sending the blocks to the client is too slow), it will be disconnected.
=> Implement `eth_subscribe` for `newHeads`

zilliqa/src/consensus.rs, zilliqa/src/message.rs, zilliqa/src/node.rs, zilliqa/tests/it/main.rs, zilliqa/tests/it/unreliable.rs
Votes can arrive for blocks we aren't yet aware of in (at least) two circumstances:
* If we disconnect and reconnect, we will download the blocks we missed, but nodes might send us their votes for the next block before we've received the missed blocks.
* Due to network latency, a vote for a block proposal could arrive before the block proposal itself.
Before this commit, the node ignores these votes and the network eventually recovers via a new view. However, this slows things down so we should recover faster if possible. Instead, we store votes for unknown blocks in memory and replay them if the block later becomes known to us.
The implementation is fairly straight forward but there are a few caveats and TODOs:
* The return type of `Consensus::proposal` is now more complicated, as it …
=> Buffer votes for blocks we don't know about

zilliqa/src/api/types/zil.rs, zilliqa/src/consensus.rs, zilliqa/src/exec.rs, zilliqa/src/scilla.rs, zilliqa/src/transaction.rs
```rust
/// If the transaction was a call to a Scilla contract, whether the called contract accepted the ZIL sent to it.
pub accepted: Option<bool>,
/// Errors from calls to Scilla contracts. Indexed by the call depth of erroring contract.
pub errors: BTreeMap<u64, Vec<ScillaError>>,
/// Exceptions from calls to Scilla contracts.
pub exceptions: Vec<ScillaException>,
```
=> Add `accepted`, `errors` and `exceptions` to Scilla receipts

zilliqa/src/api/ots.rs, zilliqa/src/api/types/eth.rs, zilliqa/src/consensus.rs, zilliqa/src/crypto.rs, zilliqa/src/db.rs, zilliqa/src/exec.rs, zilliqa/src/inspector.rs, zilliqa/src/lib.rs, zilliqa/src/node.rs, zilliqa/src/state.rs, zilliqa/tests/it/contracts/CallingContract.sol, zilliqa/tests/it/main.rs, zilliqa/tests/it/ots.rs
This is quite similar to the old implementation that I removed. When voting on a block proposal, we run transactions with an `Inspector` which records the 'touched' addresses and stores them in a separate index. This occurs for both EVM and Scilla transactions.
=> Implement `ots_searchTransactions{Before,After}`

README.md, zilliqa/src/api/ots.rs, zilliqa/src/inspector.rs, zilliqa/src/node.rs, zilliqa/tests/it/contracts/ContractCreatesAnotherContract.sol, zilliqa/tests/it/ots.rs
This API returns the 'creator' of a given contract. For Scilla contracts and most EVM contracts this is trivial - It is just the `from_addr` of the transaction which created the contract.
However, some EVM contracts are created by other contracts.
Therefore, we implement this by looping through the transactions which 'touched' the contract address and replaying each transaction. When replaying, we use a new `Inspector` to record the creator of a contract if one is created. When we find the transaction which created this contract, we can terminate.
I haven't added a test case for creating a Scilla contract yet, because I don't want to slow the test suite down more. :(
=> Implement `ots_getContractCreator`

zilliqa/src/api/types/zil.rs, zilliqa/src/api/zil.rs, zilliqa/src/exec.rs, zilliqa/src/scilla.rs, zilliqa/src/transaction.rs
Previously, when the Scilla interpreter queried an account's balance, we would return the result in units of (10^-18) ZILs. Scilla expects the result in units of (10^-12) ZILs.
To mitigate similar bugs in the future, I have introduced a newtype for quantities of ZIL expressed in units of (10^-12) ZILs: `ZilAmount`. The intention is that we continue to use `u128` in most places (e.g. for internal storage of amounts and for EVM transactions), where we continue to expressed amounts as (10^-18) ZILs. But for places we know we want amounts expressed as (10^-12) ZILs (such as the Zilliqa API requests and responses), we use `ZilAmount` to make that clear. A `ZilAmount` can't be converted to a `u128` without multiplying it by `(10^6)` and vice-versa.
=> Fix precision of account balances provided to Scilla

.github/workflows/ci.yaml, Cargo.lock
We were using nightly everywhere, because `cargo fmt` requires it with our `rustfmt.toml` configuration. However, this causes other unintended problems, such as:
* Code failing on new nightly clippy lints which aren't yet stable
* Libraries using latest nightly features when they detect a nightly compiler.
Instead, we run compilation and tests with the normal stable compiler that is specified in `rust-toolchain.toml`.
=> Use stable rust compiler in CI for everything except formatting

README.md, zilliqa/src/api/mod.rs, zilliqa/src/api/ots.rs, zilliqa/src/api/types/ots.rs, zilliqa/src/exec.rs, zilliqa/src/inspector.rs, zilliqa/tests/it/ots.rs
This replays the specified transaction with a custom `Inspector` that produces a trace in the desired format.
I haven't added a test case for creating a Scilla contract yet, because I don't want to slow the test suite down more. :(
=> Implement `ots_traceTransaction`

README.md, zilliqa/src/api/types/zil.rs, zilliqa/src/api/zil.rs
I left a bunch of the fields at `0` because calculating them is hard and requires us to store extra data. #860 tracks fixing them.
=> Implement `GetBlockchainInfo`

.github/workflows/ci.yaml, Cargo.lock, Cargo.toml, deployer/Cargo.toml, deployer/README.md, deployer/src/commands.rs, deployer/src/lib.rs, deployer/src/main.rs, deployer/src/utils.rs
Currently we have two commands:
* `new <name> <gcp_project> <gcs_bucket>` creates the TOML configuration file for a network. This is used by other commands and intended to be checked into git somewhere.
* `upgrade <config_file>` upgrades a network, based on the values from the configuration file. It will build a ZQ2 binary at the configured revision, upload it to GCS and upgrade the binaries on each VM instance.
=> Add 'deployer' tool to perform network upgrades

zilliqa/src/api/eth.rs, zilliqa/src/api/to_hex.rs, zilliqa/src/api/types/eth.rs, zilliqa/src/api/types/zil.rs, zilliqa/src/api/zil.rs, zilliqa/src/blockhooks.rs, zilliqa/src/exec.rs, zilliqa/src/message.rs, zilliqa/src/node.rs, zilliqa/src/pool.rs, zilliqa/src/scilla.rs, zilliqa/src/state.rs, zilliqa/src/transaction.rs, zilliqa/tests/it/zil.rs
I added newtypes for both `EvmGas` and `ScillaGas` to prevent confusion between them and ensure we convert at the correct exchange rate (420:1).
=> Charge gas for Scilla transactions

zilliqa/src/api/types/zil.rs, zilliqa/src/api/zil.rs, zilliqa/src/exec.rs
This API returns the list of smart contracts deployed by a given account.
I have chosen to replicate the ZQ1 implementation and exclude EVM contracts, but maybe we should include them? In this case, should we just include direct creations or also creations via other contracts?
=> Implement `GetSmartContracts`

zilliqa/src/api/types/zil.rs
Previously we returned `DsBlockRate`, but the capitalisation is sadly inconsistent in the existing API and we need to return `DSBlockRate`.
=> Fix field name in `GetBlockchainInfo` response

.github/workflows/ci.yaml, scripts/js_test.sh
The Scilla-image swizzling was pointless and caused the runner to run out of disk space. We will run Scilla properly once we start making these tests pass.
=> Fix JS test suite

zilliqa/src/api/types/eth.rs
These fields are documentation as optional rather than nullable and this behaviour matches the implementation in ZQ1.
=> Exclude some `null` fields from `eth_getTransactionByHash`

zilliqa/src/db.rs
This makes large state manipulations faster to flush to disk. This is particularly useful for the ZQ1->ZQ2 state converter.
=> Support batch trie insertions into sled

README.md, docker-compose.yaml, zilliqa/src/api/types/zil.rs, zilliqa/src/api/zil.rs
- Added JSON RPC Error codes as defined in ZQ1.
- Now, when "Txn Hash not Present" is encountered in the GetTransaction function, it returns the error code -20 (RpcDatabaseError). This ensures consistency with ZQ1 SDK to receive the same error code.
- The version value returned by GetTxResponse is converted to a string. This is also fixed by the https://github.com/Zilliqa/zq2/pull/885.
- Some minor doc and docker-compose build fix
=> 893 fix z2 perf async transfers

zilliqa/src/api/to_hex.rs, zilliqa/src/api/types/zil.rs
* `version` should be a string.
* `senderPubKey` should be a compressed SEC1 encoed point.
* `signature` should be prefixed with `0x`.
=> Fix formatting in `GetTransaction` response

zilliqa/src/api/eth.rs, zilliqa/src/consensus.rs, zilliqa/src/node.rs, zilliqa/src/pool.rs, zilliqa/tests/it/eth.rs
When the block number is `pending`, we also count the transactions in the mempool.
=> Make `eth_getTransactionCount` respect the `pending` block number

zilliqa/tests/it/consensus.rs
All of the failures I identified were just multiple 'unlucky' runs where many messages get dropped. So I've just increased the time we wait before failing.
This shouldn't meaningfully increase the runtime of the test since these situations only occur rarely and will only affect a small proportion of test seeds.
=> Make `block_production_even_when_lossy_network` test more reliable

zilliqa/src/api/eth.rs, zilliqa/src/consensus.rs, zilliqa/src/node.rs, zilliqa/src/pool.rs, zilliqa/tests/it/eth.rs
This appears to cause a significant drop in the pass rate for sharding-related tests. While we investigate the cause, lets revert the change in main and add it back once we understand what is going on.
This reverts commit e12f2b2db21842334fd8eb5cd248b37c8793dbcb.
=> Revert mempool transaction re-injection

scripts/setenv, z2/README.md, z2/src/bin/z2.rs
`z2` prints a note advising to run it using `scripts/z2` for resource accessibility.
Add a `z2` README.md and `setenv` setup.
=> feat(z2): print a note when you run z2 directly

Cargo.lock, zilliqa/Cargo.toml, zilliqa/src/api/mod.rs, zilliqa/src/api/ots.rs, zilliqa/src/api/trace.rs, zilliqa/src/consensus.rs, zilliqa/src/exec.rs, zilliqa/src/inspector.rs, zilliqa/src/node.rs, zilliqa/src/state.rs, zilliqa/src/transaction.rs
This mostly relies on the supporting code in alloy and `revm-inspectors`. I did have to do some work on our side to split the existing `TransactionApplyResult` into an `Evm` and `Scilla` variant, so we can get at the necessary data to build a replay for EVM transactions.
Support for Scilla transactions will come next.
=> Implement `trace_replayTransaction`

zilliqa/src/exec.rs, zilliqa/src/scilla.rs, zilliqa/src/state.rs
Previously when we applied a Scilla transaction to state (via `State::apply_transaction_scilla`), the state would be mutated directly by execution engine while the transaction was run. This differed from the behaviour of EVM transactions, where the execution engine only read from the state and kept changes to state in memory (in a `HashMap<Address, Account>`). This PR updates Scilla execution to work in the same way.
The advantage of this approach is that we get a state diff when executing a transaction, which makes implementing APIs similar to `trace_replayTransaction` possible. It also avoids more roundtrips from/to the database, since each account is loaded at most once and then saved once at the end of execution.
=> Refactor Scilla transaction execution

Cargo.lock, zilliqa/Cargo.toml, zilliqa/src/exec.rs, zilliqa/src/inspector.rs
These crates share a large chunk of their dependencies, so it makes sense to update them all in tandem.
Version updates for:
* alloy-consensus
* alloy-eips
* alloy-genesis
* alloy-primitives
* alloy-rpc-types
* alloy-rpc-types-trace
* alloy-serde
* alloy-sol-macro
* alloy-sol-macro-expander
* alloy-sol-macro-input
* alloy-sol-types
* c-kzg
* revm
* revm-inspectors
* revm-interpreter
* revm-precompile
* revm-primitives
* secp256k1
* secp256k1-sys
* syn-solidity
=> Update alloy and revm

.github/workflows/docker-release.yaml, Dockerfile
Rudimentary process to build and push the zq2 docker images as per issue #937 defines.
Will open follow-up issues for:
1. add an image test step
2. export the version as env variable so the software can use it as input for specifying the version
3. use the image to run the tests
=> (feat): Create the docker image for zq2 node

eth-trie.rs/src/nibbles.rs, eth-trie.rs/src/trie.rs
This is a pre-requisite for flattening Scilla storage and I figured it would make things smoother to submit it as a separate commit first.
I've tried to include explanatory comments in the code itself - Do complain if the implementation isn't clear as it is easy to get wrong and thus very possible that I have messed something up.
=> Implement `iter_by_prefix` for `EthTrie`

zilliqa-macros/src/test.rs
The tests only fail for taking 'too long' once they've actually completed anyway. This means you can have tests that pass, but exit with a failure.
We can enforce a test timeout in CI if we wish, but I don't think doing it directly in the test suite is sensible.
=> Remove test timeout

Cargo.lock, zilliqa/Cargo.toml, zilliqa/src/p2p_node.rs
It doesn't really make sense to use JSON given there isn't a convenient way for a human to read these messages anyway. And JSON payloads will be much larger than binary.
=> Encode P2P messages with CBOR instead of JSON

z2/src/converter.rs, zilliqa/src/api/eth.rs, zilliqa/src/api/types/zil.rs, zilliqa/src/consensus.rs, zilliqa/src/transaction.rs
When filling a block with transactions from the mempool, we stop taking transactions once the block gas limit is reached.
Resolves #967
=> Enforce block gas limit and keep track of cumulative gas used

README.md, zilliqa/src/bin/zilliqa.rs
After some discussion with Mauro, we realised that node configuration can be split broadly into two categories:
* Stuff that never changes and should have the same values across all nodes in a network - e.g. configuration for the genesis block.
* Stuff that is specific to each node - e.g. port configuration, enabled APIs.
We decided that a simple way to handle this split was to allow multiple configuration files which get merged by the application.
We deliberately ban configuration keys from occurring in more than one file. Therefore, no inheritance or overriding occurs when merging.
=> Merge configuration files if more than one is passed

eth-trie.rs/src/trie.rs, z2/src/converter.rs, zilliqa/src/api/eth.rs, zilliqa/src/api/ots.rs, zilliqa/src/api/zil.rs, zilliqa/src/consensus.rs, zilliqa/src/exec.rs, zilliqa/src/node.rs, zilliqa/src/scilla.rs, zilliqa/src/scilla_proto.rs, zilliqa/src/state.rs
Previously, we would serialise the full `BTreeMap` representing a Scilla contract's storage to disk and deserialise the same thing to memory whenever we needed it. Now, we flatten the map (concatenating the map indices) and store the values in a contract-specific trie. This is closer to how EVM contract storage works and means we can partially load/write a Scilla contract's storage. Also, it means the state deltas generated by our execution engine only need to store what was actually changed.
`Account` changes to always have a `storage_root` (since both EVM and Scilla contracts now store their state in a trie). `code` is now split into an enum which differentiates between EVM and Scilla contracts. Note that Scilla contracts also store their `init_data` and type information here.
I'm …
=> Flatten Scilla contract storage on disk

z2/src/converter.rs, zilliqa/src/api/types/zil.rs, zilliqa/src/consensus.rs, zilliqa/src/db.rs, zilliqa/src/exec.rs, zilliqa/src/inspector.rs, zilliqa/src/scilla.rs, zilliqa/src/transaction.rs
We maintain a call stack of Scilla contract calls. When the interpreter returns a message, we add it to the end of the call stack. We also keep track of all calls so we can add them to the transaction receipt.
Resolves #920
=> Implement intra-contract Scilla calls

zilliqa/src/transaction.rs
Previously, our `serialize` and `deserialize` implementations were incompatible. The `serialize` implementation uses `serialize_bytes`. The `deserialize` implementaion delegated to `Vec<u8>`'s implementaion, which calls `deserialize_seq` internally. In JSON, these resulted in the same serialized form but the same is not true for CBOR, which specialises `serialize_bytes` to be more efficient.
Now we correctly call `deserialize_bytes` in the `deserialize` implementation.
=> Fix transaction deserialization

Cargo.lock, zilliqa/Cargo.toml, zilliqa/benches/it.rs, zilliqa/src/node.rs
Once #1044 we should be saturating our CPU with blocks when syncing, so in theory the bottleneck will be block processing.
This adds a benchmark to measure the speed of block processing.
We can think about running this benchmark and systematically recording the processing speed in CI later.
Relates to #968
=> Add benchmark for block processing

zilliqa/Cargo.toml, zilliqa/src/p2p_node.rs
This lets us specify bootnode addresses with `/dns*` multiaddrs.
=> Support DNS resolution in libp2p

Cargo.lock, zilliqa/Cargo.toml, zilliqa/src/p2p_node.rs
The changes in #992 should have done this, but I missed that broadcasts use a separate code path and thus still use JSON. This change switches to CBOR for everything.
=> Replace JSON with CBOR for broadcasts

docs/api/eth/eth_call.doc.md, docs/api/eth/eth_getBalance.doc.md, docs/api/eth/eth_getCode.doc.md, docs/api/eth/eth_getStorageAt.doc.md, docs/api/eth/eth_getTransactionCount.doc.md, evm_scilla_js_tests/test/rpc/eth_getBlockByNumber.ts, z2/resources/api_macros.tera.md, zilliqa/src/api/erigon.rs, zilliqa/src/api/eth.rs, zilliqa/src/api/ots.rs, zilliqa/src/api/trace.rs, zilliqa/src/api/types/mod.rs, zilliqa/src/api/zil.rs, zilliqa/src/message.rs, zilliqa/src/node.rs, zilliqa/tests/it/consensus.rs, zilliqa/tests/it/persistence.rs
We now support a `BlockId` for the following APIs:
* `eth_call`
* `eth_getBalance`
* `eth_getCode`
* `eth_getStorageAt`
* `eth_getTransactionCount`
I couldn't resist making a few related changes at the same time:
* We've deleted our `BlockNumber` and now use alloy's `BlockNumberOrTag` instead.
* `Node` is now much pickier about how blocks and state are accessed. Previously, there were many overlapping ways of getting the same blocks or state. Now, everything goes through `get_block` or `get_state`. A load of unused methods have also been removed thanks to this change.
=> Implement EIP-1898

zilliqa/src/p2p_node.rs
We already ignore loopback addresses, but since we've started deploying in Docker, nodes also now listen on 172.17.0.1 which is in one of the private address ranges (172.16.0.0/12). The behaviour of the Identify protocol is that a node advertises all addresses it could possibly be reached on and leaves it to the client to select the sensible ones. Therefore, we now ignore private addresses too.
=> Ignore advertised private addresses from other nodes

zilliqa/src/consensus.rs
A debug log for this case seems quite reasonable, given it will only output once per block and is quite useful for debugging.
=> Log at debug level if we receive a proposal we cannot vote on

zilliqa/src/api/ots.rs
I broke these in #1079. Turns out they should only accept a JSON number, not a string.
=> Fix parameter types for `ots_getBlock{Details,Transactions}`

infra/tf/main.tf, infra/tf/modules/node/scripts/node_provision.py.tpl, infra/tf/validators.tf, z2/src/setup.rs, zilliqa/src/cfg.rs, zilliqa/src/p2p_node.rs
In the proto-testnet we are observing nodes learning about the
wrong external address for themselves, reporting the wrong thing
and thus other nodes failing to send messages to them.
I believe this is due to a bug in `libp2p-identify` where incoming
TCP ports are reported as the observed address of a node. However,
I think (and the documentation states) we shouldn't be relying on
other nodes to tell us our external address anyway since it is
easily exploitable by a malicious node.
So for now, we let configuration specify a nodes external address
and surpress the existing behaviour in this case.
In future, we can remove the configuration requirement by using
`libp2p-autonat` (https://github.com/Zilliqa/zq2/issues/1101).
=> Specify external address in configuration

zilliqa/src/consensus.rs
This will fix https://github.com/Zilliqa/zq2/issues/1106 which also describes why our timeouts take 4x longer than they should.
=> fix too long consensus timeouts

zilliqa/benches/it.rs, zilliqa/src/block_store.rs, zilliqa/src/consensus.rs, zilliqa/src/node.rs
Previously, we requested missing blocks from a random node in the consensus committee. Now, we can request blocks from any node who has told us they have a block with at least that view.
In future, we can extend this logic by:
* Taking into account latency, bad responses, etc. when choosing peers.
* Extending the P2P protocol so that non-validator peers can share their 'best' block with each other, meaning we can download blocks from those non-validators.
Resolves #1097 since this was the only thing we used `get_random_peer` for.
=> Select nodes to request blocks from more intelligently

zilliqa/src/block_store.rs
`requested_blocks` is only incremented when we request missing blocks but decremented when we receive any block, including a new block proposal. This means underflow is possible.
As a temporary workaround, just use a saturating subtraction. This will mean we don't perfectly account for the current number of requested blocks when selecting a peer, but this code will soon change in my next PR.
=> Fix underflow of requested block count

deny.toml
A new security advisory was just published today:
https://rustsec.org/advisories/RUSTSEC-2024-0346
This is flagged by our CI so all builds are failing.
The affected crate, `zerovec-derive`, is patched in version 0.10.4 but this hasn't been published on crates.io yet. Thus, add an exception to ignore the security advisory. The issue only becomes relevant with rust 1.80.0 which I don't believe we are using for deployment.
New issue created to revert the ignore once the crate gets updated: #1153
=> Temporarily ignore new security advisory

zilliqa/src/consensus.rs
Finalization requires a one-direct chain and a subsequent block. A two-direct chain is the common case but it is not required for committing a block.
=> fix block finalization rule

zilliqa/src/db.rs
* Change storage of timestamps within the DB to use a serialisation of Rust's `std::time::Duration` since the unix epoch
* Change type of timestamps within the db to be `BLOB`
=> Change storage of timestamps within the database to be a serialisation of Rust's Duration

zilliqa/src/consensus.rs, zilliqa/src/contracts/mod.rs, zilliqa/src/crypto.rs, zilliqa/tests/it/main.rs, zilliqa/tests/it/staking.rs
Should now be the first state change that happens in every block. Fixes #1143.
Also adds a test for it.
=> Fix second location of apply_rewards happening after transaction execution

Dockerfile, rust-toolchain.toml
Required by new `revm` versions
=> Update Rust version to 1.79.0

Cargo.lock
* Update `openssl` and `openssl-sys` to latest version
* Fixes failing GitHub actions
=> Update OpenSSL version

.github/workflows/docker-release.yaml, zilliqa/src/block_store.rs
`max` instead of `min` meant we would send a request for a very high view, only a few of the requests blocks would actually get sent and we would get stuck. Oops :)
=> Fix `to` parameter of block requests

.github/workflows/docker-release.yaml, z2/src/docgen.rs, z2/src/setup.rs, zilliqa/benches/it.rs, zilliqa/src/block_store.rs, zilliqa/src/cfg.rs, zilliqa/src/consensus.rs, zilliqa/src/node.rs, zilliqa/src/node_launcher.rs, zilliqa/src/p2p_node.rs, zilliqa/tests/it/main.rs, zilliqa/tests/it/persistence.rs
This required quite a lot of additional machinery in order to inform the `BlockStore` of request failures, so it can retry.
Now, whenever we send a direct external message in `node.rs`, we remember a `request_id` which is returned to the caller. One level up, we keep a correspondence of our generated `request_id` to libp2p's request ID. When a request succeds or fails, we can look up the `request_id` in this map and pass it back down the stack to inform the initial caller of the result.
We've also changed the type which gets sent from the network layer to the `node.rs` layer from an `ExternalMessage` to a `Result<ExternalMessage, OutgoingMessageFailure>`. The `Err` half is how failed messages are passed down.
=> Retry failed block requests

zilliqa/src/api/eth.rs, zilliqa/src/consensus.rs, zilliqa/src/node.rs, zilliqa/src/pool.rs, zilliqa/tests/it/eth.rs
* Fixes https://github.com/Zilliqa/zq2/issues/902
* Add test for `eth_getTransactionCount` to verify that it respects the expected behavior when a block number of `pending` is passed
=> Change eth_getTransactionCount to respect the pending block number 

zilliqa/src/api/eth.rs
* Fixes https://github.com/Zilliqa/zq2/issues/1171
* Return an empty list when eth_getLogs is called with future blocks, matching behaviour of other EVM based chains
=> Fix panic in eth_getLogs when called with future blocks

Cargo.lock, z2/Cargo.toml, zilliqa/Cargo.toml, zilliqa/src/api/types/ots.rs, zilliqa/src/exec.rs, zilliqa/src/inspector.rs
* `alloy-consensus`: 0.1.3 -> 0.2.0
* `alloy-eips`: 0.1.3 -> 0.2.0
* `alloy-primitives`: 0.7.2 -> 0.7.7
* `alloy-rpc-types-trace`: 0.1.3 -> 0.2.0
* `revm-inspectors`: 0.3.0 -> 0.5.3
* `revm`: 10.0.0 -> 12.1.0
=> Update alloy and revm dependencies

infra/tf/locals.tf, z2/src/setup.rs, zilliqa/src/bin/convert-key.rs, zilliqa/src/crypto.rs, zilliqa/tests/it/main.rs, zilliqa/tests/it/persistence.rs, zilliqa/tests/it/staking.rs
The key is intended to be a signing key for the physical node - and not tied to any on-chain account. In the test framework and in z2, a separate key is now generated for each validator's on-chain account.
=> Remove ECDSA methods from SecretKey.

.gitattributes
It's a generated file so can effectively be treated as binary - specifically, we pretty much never need an explicit line-by-line diff. Thus this is set in the .gitattributes file. Hopefully, this should make diffs on pull requests display relevant linecounts, rather than exploding into the tens of thousands whenever contracts are recompiled and thus hiding the true change size.
If this works, this could also be added to Cargo.lock files, though their impact on diffs is usually minor so I left that for now.
=> Attempt to remove the contracts.json from git diff linecounts.

docs/api/zilliqa/getsmartcontractcode.doc.md, zilliqa/src/api/zil.rs
* Fixes https://github.com/Zilliqa/zq2/issues/1027
* Return EVM code from `GetSmartContractCode` by encoding the bytecode as hexadecimal
=> Change GetSmartContractCode to return EVM code

CHANGELOG.md, zilliqa/src/api/zil.rs, zilliqa/src/cfg.rs
I fixed a small bug in the `if` condition which would cause the limit to be ignored. Instead we just represent the unlimited size directly in `cfg.rs`. Also, the default behaviour is now that no limit is set, to match the existing behaviour of ZQ1.
I also added a changelog entry for the change.
=> Fix response size limiter for `GetSmartContractState`

CHANGELOG.md, zilliqa/src/bin/zilliqa.rs
This ensures that when a node panics, the panic message and backtrace is logged as JSON (if JSON logging is enabled) and thus we can see the panic in the node's logs (in GCP).
Example of output:
```
{"timestamp":"2024-08-12T18:10:57.077806Z","level":"ERROR","fields":{"thread_name":"main","message":"At least one shard must be configured","panic.file":"zilliqa/src/bin/zilliqa.rs","panic.line":94,"panic.column":5,"backtrace":"   0: zilliqa::main::{{closure}}::{{closure}}\n             at ./zilliqa/src/bin/zilliqa.rs:46:25\n   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call\n             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2036:9\n   2: std::panicking::rust_panic_with_hook\n             at …
```
=> Record panics with a `tracing` event

Cargo.lock, docker-compose-networking-test.yaml, infra/config_networking_test.toml, z2/Cargo.toml, zilliqa/Cargo.toml, zilliqa/src/p2p_node.rs
- Plus docker compose file and config file used for testing
- Using autonat v1 since v2 didn't seem super mature yet
Closes #1101
The docker compose file is used for testing the network without mDNS. I actually just commented out mDNS for testing, we could try to block it in the compose file if we need that capability in future.
=> Integrate Autonat

zilliqa/src/consensus.rs
I haven't worked out why this occurs in proto-testnet yet, but this means the whole node doesn't panic and we instead just log the problem.
I've also added logs when we cleanup votes in case that is the cause of the problem.
=> Fail gracefully if we try to propose a block without any votes

z2/src/converter.rs, zilliqa/benches/it.rs, zilliqa/src/api/types/eth.rs, zilliqa/src/block_store.rs, zilliqa/src/consensus.rs, zilliqa/src/db.rs, zilliqa/src/message.rs, zilliqa/src/node.rs
Instead we move the block's `QuorumCerticiate` into the `BlockHeader`. The `block_hash` in the `QuorumCertificate` is always the block's parent hash.
=> Remove redundant `parent_hash` from `BlockHeader`

zilliqa/src/consensus.rs
Previously, we would always wait a full 1s after reaching a supermajority of votes, even if reaching that supermajority had taken a significant amount of time. This meant that block times were greater than the `empty_block_timeout`.
=> Avoid waiting too long before attempting to propose an empty block

Cargo.lock, zilliqa/Cargo.toml, zilliqa/src/api/zil.rs
- Fixes https://github.com/Zilliqa/zq2/issues/1241
- Accept bech32 address in APIs:
- `GetBalance`
- `GetSmartContractState`
- `GetSmartContractSubState`
- `GetSmartContractInit`
- `GetSmartContractCode`
- `GetSmartContracts`
=> Accept bech32 address in some APIs

z2/src/deployer.rs
`Bootstrap` and `Validator` are the roles responsible for proposing and voting on blocks. By performing these upgrades close to each other, we ensure minimum offset between the times they start up. In cases where the network has crashed, this minimises the time for the nodes to sync up their views again and restart the production of blocks.
=> Reorder `NodeRole`s to make `Validator` adjacent to `Bootstrap`

CHANGELOG.md, zilliqa/src/exec.rs
`revm` relies on querying the `code_hash` even if the `code` isn't `None`, meaning we need to set it correctly.
Also, we are now more lenient when applying deltas in `apply_delta_evm` by accepting `code = None` if `code_hash = KECCAK_EMPTY`.
=> Correctly calculate code_hash for EVM contracts

CHANGELOG.md, zilliqa/src/block_store.rs
`BlockStore` now stores unserviceable requests in a set. Otherwise when we don't have any peers for an extended period of time, the list fills up with duplicate requests for the same range of blocks.
This also means we now service the requests in a more sensible order (lowest view to highest view).
=> Deduplicate unserviceable requests

CHANGELOG.md, zilliqa/src/api/types/zil.rs, zilliqa/src/api/zil.rs, zilliqa/tests/it/zil.rs
Adds GetTxBlockRate, and alters GetDSBlockRate to be based off the TX rate.
I initially implemented this by querying the DB to count the number `n` of blocks in the last hour, and then returning n/3600, but I've now altered it to instead work out the time `t` since the 5th from last block, and then calculating 5/t. Both methods have pros and cons in terms of complexity, accuracy, speed etc, but this method of using a fixed number of blocks seemed better overall. The main pros were that it only requires accessing one block, doesn't require much in the way of special cases for young networks, and doesn't require additional DB code. 
I've also added a simple test to check we're getting roughly the right thing back
=> Add `GetTxBlockRate` API to return the current transaction block rate.

CHANGELOG.md, zilliqa/src/consensus.rs, zilliqa/src/message.rs
This change introduces early Proposal block assembly by separating the step into two (2) phases: a) block assembly; and b) rewards application.
The feature is triggered whenever a Vote is received by the Leader. This allows the Leader several opportunities to (a) assemble the Proposal, before super-majority is reached. The early Block will be assembled with any ready transactions from the pool. When super-majority is reached (b) the rewards are applied and the final block is produced with the majority QC.
=> Early-Proposal

Cargo.lock, z2/Cargo.toml, z2/docs/README.md, z2/docs/deployer.md, z2/resources/chain-specs/zq2-perftest.toml, z2/src/bin/z2.rs, z2/src/chain.rs, z2/src/deployer.rs, z2/src/lib.rs, z2/src/node.rs, z2/src/plumbing.rs, z2/src/validators.rs, zq2-devnet.yaml, zq2-infratest.yaml
- add perftest and infratest networks
- improve network install/update errors verbosity
- implement `z2 deployer deposit` command to deposit the stake amount on all the network validators
- run network install/update in parallel on all nodes except for bootstrap and apps nodes
- parallelise `z2 deployer get-deposit-commands` execution
- enhance z2 CLI command descriptions
- enhance z2 CLI documentation
=> feat: DEVOPS-1521 implement z2 deployer deposit command

Cargo.lock, eth-trie.rs/Cargo.toml, z2/Cargo.toml, zilliqa/Cargo.toml, zilliqa/src/node.rs
revm depends on a later version of the `blst` native library than the latest published version of `blsful`. Therefore, I have forked `blsful` to update `blst` to the same version (via the intermediate `blstrs_plus` dependency). The PR to merge this upstream is open and I will remove the git dependency once these PRs are merged and released.
=> Update alloy, revm and other dependencies

zilliqa/src/db.rs
PR #1366 attempted to do this, but it didn't quite work because `load_trusted_checkpoint` still tries to add the checkpoint block to the database, which fails due to breaking the `UNIQUE` constraint on the table. Instead, if the block already exists in the database we return early without loading any state from the checkpoint file.
=> Make checkpoint loading idempotent

CHANGELOG.md, zilliqa/src/db.rs
I'm hoping this avoids us making incomplete mutations to the state trie, leading to inconsistent data.
=> Apply state changes in a database transaction

zilliqa/src/cfg.rs
This is the quick fix so that the default value can be set without a crash. 
This doesnt fix the wider issue of u64 being an unsuitable type for all configuration values.
=> fix: default state_rpc_limit to isize maximum 

CHANGELOG.md, zilliqa/src/consensus.rs
This has two benefits:
1. We avoid putting blocks in our database which would fail the later check.
2. The changes to state are only flushed to disk when we calculate the state root hash. By calculating the state root hash of the block before storing that block, we ensure we aren't storing a block with unflushed state. This fixes a source of database inconsistency.
=> Move state root hash check for blocks earlier

zilliqa/src/node.rs
When a request fails, the `PeerId` in the failure is the peer we were sending that request `to`.
=> Fix naming in message failure handler log

zilliqa/src/consensus.rs, zilliqa/src/node_launcher.rs, zilliqa/src/p2p_node.rs
Instead of unwrap i've converted any potential errors to error logs. There are no expected errors here but we we should avoid a crash if there is.
=>  Do not blindly unwrap processing of network messages

z2/resources/node_provision.tera.py
To reduce the number of unused metrics ($300 USD in devnet and $500 USD in testnet), first we need to exclude non-used metrics.
https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/configuration#metrics-config
To further optimize the collection costs, we can eventually exclude more metrics inside the disks, memory and cpu scopes and reduce the scraping frequency (currently 60s).
As a plan B for the future probably a OTEL or Prometheus exporter could give us the same values with a more efficient pricing model.
=> feat: DEVOPS-1574 ops agent metrics config to exclude non-used metrics

CHANGELOG.md, zilliqa/tests/it/zil.rs
The main intention here was to create an example test for testing transactions (`test_simulate_transactions`), since I thought something fishy was going on with the transaction tests. While I was at it I added a few more tests using the same methodology. I also identified that the strange behaviour I'd noted was due to 0 vs 1 based page numbers in `get_txns_for_tx_block_ex`, and I've now fixed the test to respect that.
- `get_txns_for_tx_block_0`
- `get_txns_for_tx_block_ex_1`
- `test_simulate_transactions`
- `get_tx_rate_1`
- `get_tx_block_rate_1`
- Some removals of duplicated asserts
=> Add more API tests

CHANGELOG.md, zilliqa/src/api/eth.rs, zilliqa/src/api/types/eth.rs
`eth_call` and `eth_estimateGas` now accept `input` as well as `data`. If both fields are passed, we expect them to have the same value and return an error if not.
=> Accept `input` or `data` for transaction request payloads

zilliqa/src/consensus.rs
The original `execute_block()` collected verified transactions transactions from the Proposal block by re-verifying each transaction in the Proposal block. This triggers the `recover_signer()` library call for each transaction in the Proposal. It then fills up any missing ones from the mempool by cloning.
This PR flips this behaviour around to collect verified transactions first from the mempool, which already contains pre-verified transactions. It then fills up any missing ones from the Proposal block by only re-verifying those missing from the mempool.
This speeds things up by several orders of magnitude, when the transactions are already pre-verified and present in the mempool, with the worst case scenario being similar in timing to the previous behaviour e.g.
before
```
zilliqanode1 …
```
=> Reduce time taken to collect VerifiedTransactions

zilliqa/src/cfg.rs, zilliqa/src/consensus.rs, zilliqa/src/node.rs, zilliqa/tests/it/persistence.rs
Closes https://github.com/Zilliqa/zq2/issues/1218
The overall goal is to stop blocks being created and broadcast immediately upon receive of a transaction. 
- Create `early_proposal` block proposal as soon as any Votes arrive l
- As new transactions come in update `early_proposal` to include them
- Broadcast proposal only after `empty_block_timeout` seconds have passed since last view
=> Do not immediately propose block upon receiving tx

zilliqa/src/consensus.rs, zilliqa/src/db.rs
Otherwise `deal_with_fork` gets into an infinite loop when re-executing blocks that were previously non-canonical, since `self.head_block()` is never updated.
I missed this when implementing #1449.
=> Mark blocks as canonical when we execute them

infra/config_networking_test.toml, z2/docs/converter.md, z2/resources/chain-specs/zq2-devnet.toml, z2/resources/chain-specs/zq2-perftest.toml, z2/resources/chain-specs/zq2-prototestnet.toml, z2/resources/chain-specs/zq2-uccbtest.toml, z2/resources/config.tera.toml, z2/resources/node_provision.tera.py, z2/resources/start_node.tera.sh, zilliqa/Cargo.toml, zilliqa/src/p2p_node.rs
This PR changes the underlying swarm transport from TCP to QUIC. This is also recommended by [libp2p](https://connectivity.libp2p.io/) as QUIC is faster. This has been deployed in `zq2-devnet` successfully. This is a breaking change and the entire network needs to be upgraded to QUIC.
=> Replace the TCP swarm with QUIC.

evm_scilla_js_tests/test/scilla/Timestamp.ts, z2/src/converter.rs, zilliqa/src/api/types/zil.rs, zilliqa/src/api/zil.rs, zilliqa/src/exec.rs, zilliqa/src/precompiles/scilla.rs, zilliqa/src/scilla.rs, zilliqa/src/serde_util.rs, zilliqa/src/state.rs, zilliqa/src/transaction.rs, zilliqa/tests/it/zil.rs
The scilla_read precompile now reads from either the contract state or the contract's init data when a value is queried.
To achieve this, I have changed the type of a Scilla contract's `init_data` from `String` to `Vec<ParamValue>`. The same data is stored, but we now parse the data on entry so that we can retrieve values easily later.
Also this fixes #1380
=> Read from init_data or contract state in scilla_read precompile

z2/resources/node_provision.tera.py
Previously, the check only passed if the latest returned block was greater than the previous one. Occasionally, we reset the devnet to an earlier block. This causes all the health checks to fail. So instead we just assert that the 'latest' block has changed within the last 60 seconds, even if the block number has decreased.
=> Pass health checks if any block is produced

zilliqa/src/p2p_node.rs
This makes two changes:
1. Use the default configuration for autonat. Previously, the zero `throttle_server_period` was causing us to wardial an unreachable server, causing performance problems on our side and probably pointless network traffic.
2. Increase the gossipsub duplicate cache TTL from the default of 1 minute to 5 minutes. This means we are more resilient to peers which are slow to receive a message, meaning they are slow to re-broadcast it. If the TTL is too low, we will treat this re-broadcast as a new message and re-broadcast it again ourselves causing extra network traffic.
Fixes #1632
=> Change libp2p configuration to reduce network noise

Cargo.lock, evm_scilla_js_tests/README.z2.md, evm_scilla_js_tests/hardhat.config.ts, z2/Cargo.toml, z2/resources/test_env.tera.sh, z2/src/setup.rs
Some boilerplate to allow evm_scilla_js_tests to run in z2 networks; my next move is to try to get them to pass (including the Scilla library tests) - after that if you want it should be easy enough to add them to CICD.
Do say if you want an issue filed for reference here ..
=> (feat) Run evm_scilla_js_tests with z2

docs/fetching_blocks.md, z2/resources/chain-specs/zq2-devnet.toml, z2/resources/config.tera.toml, z2/resources/start_node.tera.sh, z2/src/bin/z2.rs, z2/src/converter.rs, z2/src/deployer.rs, z2/src/node_spec.rs, z2/src/plumbing.rs, z2/src/setup.rs, z2/src/utils.rs, z2/src/validators.rs, z2/src/zq2.rs, zilliqa/src/api/zil.rs, zilliqa/src/block_store.rs, zilliqa/src/consensus.rs, zilliqa/src/constants.rs, zilliqa/src/db.rs, zilliqa/src/exec.rs, zilliqa/src/message.rs, zilliqa/src/node.rs, zilliqa/src/node_launcher.rs, zilliqa/src/p2p_node.rs, zilliqa/src/scilla.rs, zilliqa/src/time.rs, zilliqa/tests/it/consensus.rs, zilliqa/tests/it/main.rs, zq2-devnet.yaml
.. see the (rather long) commit list for a list of things this fixes.
We also add the ability for z2 to join nodes to a configured network, for debugging.
Closes #1364
=> More flexible block fetching, and a few bug fixes.

z2/src/docgen.rs, zilliqa/src/api/admin.rs, zilliqa/src/api/mod.rs, zilliqa/tests/it/admin.rs, zilliqa/tests/it/main.rs
=> (feat) Trigger checkpoints via an admin_ RPC call

zilliqa/src/message.rs
Include the view number when we print a `Vote` or a `NewView` message
=> Improve Vote and NewView logs

zilliqa/src/api/types/zil.rs, zilliqa/src/api/zil.rs, zilliqa/tests/it/zil.rs
This is a bit of a housekeeping PR - it shouldn't change functionality substantially.
I've added placeholder API functions and tests for 9 API endpoints. This is intended to make merging easier by avoiding the situation where I have a PR for one API endpoint in flight, but get merge conflicts if I try to start work on another because they're both adding to the end of the file. This approach of adding placeholders avoids the alternative of creating loads of separate files.
In addition, I've done the same thing for tests, added the return type for getminerinfo, and added comments to API endpoint functions indicating what API endpoint they service.
@JamesHinshelwood Hopefully this avoids your concerns about making things more complicated with lots of files, while still making merges easier.
=> Adds placeholders for in-progress APIs, plus comments

z2/src/perf.rs, z2/src/setup.rs, zilliqa/src/consensus.rs
(fix) consensus.rs: Put qcs in an aggregate in committee index order so that they will always validate.
(fix) perf.rs: format!() the error message correctly.
(feat) setup.ts: Give genesis accounts a decent quantity of tokens so they can be used for load tests
Relates to #1570
=> Put qcs in an aggregate in order to enable validation

zilliqa/src/consensus.rs
Currently we reject blocks whose `view <= self.view`. This means that nodes will reject then re-request the missing block later on. 
Instead, here we add outdated blocks to the `block_store`'s cache to be used later or trimmed out.
Note that we still reject blocks whose `view <= self.finalised_view()`.
=> Store block in cache when view is smaller than current

z2/runtime/start_otterscan.sh
Just runs the version stamp script if it sees one, to make sure the version file exists when otterscan tries to look for it later on.
=> (fix) Fix otterscan invocation so that it will run the first time

z2/src/converter.rs, zilliqa/src/consensus.rs, zilliqa/src/db.rs, zilliqa/src/node.rs, zilliqa/tests/it/consensus.rs, zilliqa/tests/it/persistence.rs
Closes https://github.com/Zilliqa/zq2/issues/1609 and https://github.com/Zilliqa/zq2/issues/1709.
For the purpose of reducing re-sync time after consensus has not been reached for a while. 
For example, before these changes a node on `view: 30` with `finalised_view: 10` would start from `view: 10` if restarted. Now, they'll start back on `view :30`. If enough time has passed since they went down then they will jump ahead the minimum number of views.
These changes make breaking changes to the db
=> BREAKING CHANGE: Persist node's current view in the database

zilliqa/tests/it/zil.rs
This bug causes 1/256th of test runs to fail with overflow checks enabled.
=> Fix overflow in `create_transaction_errors` test

README.md, docs/api/eth/eth_syncing.doc.md, z2/docs/README.md, zilliqa/src/api/eth.rs, zilliqa/src/api/types/eth.rs, zilliqa/src/block_store.rs, zilliqa/src/consensus.rs, zilliqa/tests/it/eth.rs
=> The eth_syncing() API call

z2/src/converter.rs
Converter with crashing with following error when we run on mainnet persistence.
```
Error: EOF while parsing a value at line 1 column 0
Stack backtrace:
0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
at /home/chetan_zilliqa_com/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.89/src/backtrace.rs:27:14
1: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1989:27
2: z2lib::converter::get_contract_code
at ./z2/src/converter.rs:205:20
3: z2lib::converter::convert_persistence::{{closure}}
at ./z2/src/converter.rs:285:24
4: z2lib::plumbing::run_persistence_converter::{{closure}}
at …
```
=> Fix converter crashing because of blank init data

zilliqa/src/api/types/zil.rs, zilliqa/src/api/zil.rs, zilliqa/tests/it/zil.rs
- Added code to get miner address
- Added comments for variables that appear obsolete in ZQ2
- Set version number to 2 (it was 1 in ZQ1 so I'm assuming it should now be 2)
- Retrieved correct values for gas_limit and gas_used
- Refactored
- Added test
This seemed to be enough changes to be worth a PR, but there are still issues with incorrect hashes which I haven't addressed yet.
Addresses #1676
=> Some fixes for get_tx_block

zilliqa/src/contracts/deposit.sol, zilliqa/tests/it/staking.rs
Implement `getTotalStake()` as per #1745, `getControlAddress()` as per #1746, as well as `setControlAddress()` and `setRewardAddress()` as defined in #1301
=> Add getter and setter functions to `Deposit` contract

zilliqa/src/api/types/zil.rs, zilliqa/tests/it/zil.rs
- event logs field now always returned
- accepted field now always returned
- transitions field now always returned
- added test
Not addressed:
- nonces sometimes different (looks like its outside the API code)
- invalid signature errors (looks like its outside the API code)
- version different (presumed acceptable)
- capitalisation different (presumed acceptable)
- cumulative_gas sometimes zero (looks like its outside the API code)
Relates to #1666
=> Some GetTransaction bugfixes

zilliqa/src/api/types/eth.rs, zilliqa/src/message.rs
- Added a version field
- Made the size field real
This is intended to close #1675.
There are still value differences remaining, I'm going to assume they're fine unless anyone knows otherwise
=> Fixes for eth_getBlockByNumber

zilliqa/src/consensus.rs, zilliqa/src/contracts/mod.rs, zilliqa/src/exec.rs
Analysis of the vote handling process on local, finds that in the case of a 4-validator network, it takes about 25ms to handle a vote. Of this, ~13ms is spent in `total_weight()` and ~7ms is spent in `get_stakers()` calls to the EVM. This represents about 80% of the overall vote handling time. Increasing the number of validators also increases the vote handling time (as observed earlier).
This PR introduces some changes:
1. Rewrite of `total_weight()` from O(n) to O(1) time, which reduced the handling time from 13ms to ~3ms by calling the `getTotalStake()` deposit contract; then adding a caching mechanism reduced this further to a negligible cost after the first call.
2. Adding caching to `get_stakers()`, which reduces the call cost to negligible, after the first call.
This brings into …
=> Faster vote handling

zilliqa/src/api/types/eth.rs
To match docs (see discussion: https://github.com/Zilliqa/zq2/pull/1763#discussion_r1834672411)
=> Removed version number field from eth_getBlockByNumber

zilliqa/src/api/types/zil.rs
Following on from discussion here: https://github.com/Zilliqa/zq2/pull/1752#discussion_r1834692023
This sets the version field to 1, as was reported to be returned by ZQ1 here: https://github.com/Zilliqa/zq2/issues/1676
=> Changed version returned by get_tx_block from 2 to 1, to match ZQ1

Cargo.lock, zilliqa/Cargo.toml, zilliqa/src/api/types/zil.rs
Updated GetTransactionStatus API endpoint to use an enum to represent possible transaction statuses
Added serde_repr to serialise to numeric representation
=> Updated GetTransactionStatus API endpoint to use an enum

.github/dependabot.yaml
Often these dependencies need to updated in lock-step to compile (since they have public dependencies on each other).
=> Group related dependabot updates together

zilliqa/src/consensus.rs
In the case of a long timeout period it is possible for all nodes to be within the same view but the leader to not have all NewView message. Eg if a node timed out recently. 
Also when a node jumps to a view after starting up again we want a `NewView` message to be sent so that consensus can continue immediately if all other nodes are on the same view. 
We send the `NewView` message here after every `consensus_timeout` seconds. Unfortunately sending the message immediately on startup fails with `DialError` which i assume is due to the peer handshakes not yet having completed.
=> Resend NewView messages after consensus_timeout seconds

zilliqa/src/block_store.rs, zilliqa/src/consensus.rs, zilliqa/src/constants.rs
The database query to calculate block availability is very slow (8 seconds on the devnet). Therefore, we now only perform this query once at start-up. We keep the result in a `RangeMap` which we keep up-to-date whenever a new block is added.
=> Don't query database for block availability

docs/api/zilliqa/getnodetype.doc.md, zilliqa/src/api/zil.rs, zilliqa/src/consensus.rs, zilliqa/tests/it/zil.rs
- Previous node types (Seed/Lookup/Not in network...) don't appear to be relevant in ZQ2, so this now returns Leader or Validator instead
- Docs updated to match
- Test added
- Closes #1538
- References #1590
=> Implement GetNodeType

zilliqa/src/api/types/zil.rs, zilliqa/src/api/zil.rs, zilliqa/tests/it/zil.rs
Docs state that this has been replace by XShard so we're just returning num_peers
Closes #1597
=> Implement GetShardingStructure

docs/api/zilliqa/getminerinfo.doc.md, zilliqa/src/api/zil.rs, zilliqa/tests/it/zil.rs
The argument type (a DS block number) and some of the return type (dscommittee) aren't things that exist in ZQ2. For that reason I've hardcoded this to return nothing and updated the docs to say this is now a placeholder.
The other option was to try and return the closest equivalent data, but on balance that felt like it might be confusing.
I'm very open to changing to that option if anyone would prefer that, though.
Closes #1537
=> Implement GetMinerInfo

zilliqa/src/block_store.rs, zilliqa/src/consensus.rs
In the scenario in which a node restarts and consensus does not continue without it, it is likely that it has a lower `high_qc` than the other nodes - if it Votes then goes offline before receiving the proposal.
`block_store` populates its peers list when it receives Proposals. So if consensus does not continue then the node never gets a chance to learn that it is behind and  thus never catches up its `high_qc`. 
When a node's `high_qc` is out of line with the other nodes then the exponential backoff will not catch it up for reasons explained in the linked ticket.
=> feat: Re-request likely missing blocks after restart

zilliqa/src/contracts/deposit.sol
The `latestComputedEpoch` determines the latest committee regardless of the `currentEpoch()`
=> Fix the logic in getFutureStake()

zilliqa/src/api/types/zil.rs, zilliqa/src/api/zil.rs, zilliqa/tests/it/zil.rs
- "Soft" isn't mentioned elsewhere in the ZQ2 codebase so this just wraps GetTransaction
- Adds a new test, and lengthenes the test for GetTransaction, but keeps them separate in case we need to modify one or both in future
- Looks like there might be a bug with stringification of addresses somewhere leading to mixed case results, but it feels outside the scope of this commit so I normalise via to_lowercase in the test
- Closes #1546
=> Implement GetSoftConfirmedTransaction

Cargo.lock, infra/otel-collector-config.yaml, zilliqa/Cargo.toml, zilliqa/src/api/mod.rs, zilliqa/src/bin/zilliqa.rs, zilliqa/src/node_launcher.rs
We will now export the `messaging.process.duration` metric which records the time spent processing P2P messages.
This also fixes a few minor issues with the existing metrics.
=> Add metric to report P2P message processing time

zilliqa/src/db.rs
`WHERE tip_info.view < ?1` will always be `FALSE` if `tip_info.view` is `NULL`. This means when starting a fresh network from a checkpoint, we fail to set the view and it is later defaulted to 0.
=> Set view if current value is NULL

zilliqa/src/consensus.rs, zilliqa/src/db.rs
I've seen that SQL insert latency is a large bottleneck for the execution of blocks with many transactions. By batching these transactions and performing them all with a single SQL query at the end of executing a block, we should reduce this latency.
=> Batch SQL inserts for transactions

z2/src/converter.rs, z2/src/zq1/persistence.rs
This adds code to support conversion of transitions.
However, it relies on adding back in the transitions field of TransactionReceipt, which may have been commented out for a reason, so I'd appreciate your input, @bzawisto
=> Fix to address missing transitions

zilliqa/src/node.rs, zilliqa/src/p2p_node.rs, zilliqa/tests/it/consensus.rs, zilliqa/tests/it/eth.rs, zilliqa/tests/it/main.rs
There was a stale code-path and comment that I forgot to remove earlier. ~~This quick PR removes it.~~ Turned out to be more work than I thought. But it's good to fix the tests, to reflect the actual code-path.
=> Removing a stale code path and comment.

Cargo.lock, z2/Cargo.toml, z2/docs/converter.md, z2/resources/chain-specs/zq2-devnet.toml, z2/resources/chain-specs/zq2-perftest.toml, z2/resources/chain-specs/zq2-protomainnet.toml, z2/resources/chain-specs/zq2-uccbtest.toml, z2/resources/config.tera.toml, zilliqa/Cargo.toml, zilliqa/src/p2p_node.rs
We now use the libp2p from github, since it includes some fixes and other features that make our networks more stable.
Also, we stop using QUIC and use TCP everywhere - We are suspicious this was the cause of the node hangs we saw in the devnet.
=> Use latest libp2p version and switch to TCP

zilliqa/src/contracts/deposit.sol
Implement the `getFutureTotalStake()` function in the deposit contract to query the amount total stake after applying all pending deposit topups and unstake operations.
=> Add `getFutureTotalStake()` function

.github/workflows/ci.yaml
The transaction benchmark takes a while to run in debug mode (by design because it generates many transactions). I didn't realise `cargo test --all-targets` would run it, which doubled CI times.
=> Don't run benchmarks in CI

zilliqa/src/contracts/deposit.sol
This shall fix #1932 which happened because the `currentWithdrawal` in the `unstake()` function "reused" an earlier withdrawal and overwrote its `timestamp` but not its `amount` so the current `amount` was added to the `amount` of that earlier `withdrawal`.
=> Fix repeated withdrawals

README.md, docker-compose.yaml, infra/config_docker.toml, zilliqa/src/state.rs
This PR does two things:
- Fixes config.toml for local/docker, due to TCP changes.
- Sets the Deposit contract to the total deposits at genesis, which was missing.
Before this fix:
```
curl -X POST   -H "Content-Type: application/json"   --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x000000000000000000005a494C4445504F534954", "latest"],"id":1}' http://localhost:4201/
{"jsonrpc":"2.0","id":1,"result":"0x0"}
```
After this fix:
```
curl -X POST   -H "Content-Type: application/json"   --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x000000000000000000005a494C4445504F534954", "latest"],"id":1}' http://localhost:4201/
{"jsonrpc":"2.0","id":1,"result":"0x2116545850052128000000"}
```
The amount 0x2116545850052128000000 is 40000000000000000000000000ZIL, which …
=> Fixed missing Genesis deposit balances.

zilliqa/src/consensus.rs
Previously, we would optimistically execute transactions from the pool, even if their gas limit exceeded the remaining gas, in case they actually used less gas after being executed.
However, this means we need to commit state after each transaction and unwind changes if our optimistic guess was wrong. Instead, we make the pessimistic assumption that transaction gas limits are accurate and don't execute a transaction unless we are guaranteed to have enough space for it.
=> Don't execute transactions unless they will definitely fit in a block

zilliqa/benches/it.rs
We create a dummy network with 2 validators - 'big' which has a large proportion of the stake and 'tiny' which has a small amount of stake. The intention is that 'big' will always be the block proposer, because the proposer is selected in proportion to the validators' relative stake. However, 'tiny' will still get to have a vote on this proposal, despite its vote not being needed to reach a supermajority. The benchmark will execute the following in each iteration:
1. Get 'big' to process the previous vote and propose a block
2. Get 'tiny' to vote on this block
3. Get 'big' to vote on this block
Step 2 is important, because we want to measure the time it takes a validator to vote on a block it hasn't seen before. In step 3, 'big' will skip most of the block validation logic because it …
=> Improve full block production benchmark

z2/src/converter.rs, z2/src/docgen.rs, z2/src/perf.rs, z2/src/perf_mod/conform.rs, z2/src/plumbing.rs, z2/src/zq1/db.rs
The extra imports were causing failures in #1992 because we import deprecated stuff and don't use it.
=> Clean up unused imports and dead code

z2/src/chain/instance.rs
.. the google cloud SDK I have installed (501.0.0) doesn't seem to like this and will abort if it finds one.
=> Pass zones to gcp as zone names rather than URLs

z2/resources/config.tera.toml, z2/src/chain/node.rs, z2/src/setup.rs, zilliqa/src/cfg.rs, zilliqa/src/consensus.rs, zilliqa/src/exec.rs, zilliqa/src/node.rs, zilliqa/tests/it/main.rs, zilliqa/tests/it/persistence.rs
This significantly improves performance on nodes which don't need to serve the `ots_` APIs.
```
produce-full/produce-full
time:   [1.0781 s 1.2170 s 1.3138 s]
thrpt:  [0.7612  elem/s 0.8217  elem/s 0.9275  elem/s]
change:
time:   [-50.851% -43.988% -35.863%] (p = 0.00 < 0.05)
thrpt:  [+55.917% +78.532% +103.46%]
Performance has improved.
```
=> Disable Otterscan indices by default

.github/workflows/base_benchmarks.yaml, .github/workflows/ci.yaml, .github/workflows/pr_benchmarks.yaml, .github/workflows/pr_benchmarks_closed.yaml
With this change, if someone pushes a new change to a branch, the previous CI runs will be cancelled in favour of running again on the latest change. This should relieve some pressure on our CI runners.
Also, I included a small change to avoid spurious failures from the "Archive closed PR branch" workflow.
=> Cancel duplicate CI runs on non-main branches

docs/api/zilliqa/dsblocklisting.doc.md, docs/api/zilliqa/getcurrentdscomm.doc.md, docs/api/zilliqa/getcurrentdsepoch.doc.md, docs/api/zilliqa/getdsblock.doc.md, docs/api/zilliqa/getdsblockrate.doc.md, docs/api/zilliqa/getdsblockverbose.doc.md, docs/api/zilliqa/getlatestdsblock.doc.md, docs/api/zilliqa/getminerinfo.doc.md, docs/api/zilliqa/getnodetype.doc.md, docs/api/zilliqa/getnumdsblocks.doc.md, docs/api/zilliqa/getnumtxnsdsepoch.doc.md, docs/api/zilliqa/getprevdifficulty.doc.md, docs/api/zilliqa/getprevdsdifficulty.doc.md, docs/api/zilliqa/getstateproof.doc.md, docs/api/zilliqa/gettxblock.doc.md
- Adds deprecation status tags to deprecated endpoints (mainly ones pertaining to DS blocks)
- Removes partially implemented status tag gettxblock, which is now implemented
=> API updates

zilliqa/src/db.rs
This will let us make breaking changes to the database format in the future, without having to write ugly code which has to guess what version of data it is reading.
=> Write database version file to disk

zilliqa/src/cfg.rs, zilliqa/src/exec.rs, zilliqa/src/precompiles/scilla.rs, zilliqa/tests/it/contracts/ScillaInterop.sol, zilliqa/tests/it/zil.rs
Despite the name `keep_origin`, the flag actually means "keep the caller of the previous call, like in an EVM `DELEGATECALL`". This fixes the behaviour to match that definition.
It is worth noting that the `keep_origin` flag is entirely pointless and complicates the precompile implementation massively. The exact same behaviour can be achieved by calling the precompile with `DELEGATECALL`, so there was no need for us to add this flag. However, contracts are now using it in the wild so we are stuck with it.
=> Fix caller of `scilla_call`s with `keep_origin = 1`

zilliqa/src/db.rs
Previously, we would append the current version to the end of the existing file, meaining subsequent runs would fail with an incompatible version. Instead, we truncate the file before writing.
=> Fix writing to database version file

zilliqa/src/consensus.rs
Set the exponential backoff timeout to be a power of 1.5. This will reduce the wait between views timing out when the view difference is  relatively large to values less ridiculous.
=> feat: set exp. backoff timeout to be a power of 1.5

zilliqa/src/consensus.rs, zilliqa/src/node.rs
In some cases where the entire network is down, many nodes will have disjoint values of their high QC. The only way for them to sync the high QCs up is to wait for a supermajority of nodes to become the leader of a missed view, meaning it receives `NewView` messages from everyone else and can updates its own high QC.
To speed this up, we now broadcast `NewView`s. We still send the first `NewView` message directly to the leader, but we broadcast repeated messages.
We also change the `NewView` processing logic to ensure nodes will update their high QC based on received messages, even if they are not the leader of the view.
=> Broadcast repeated new view messages to speed up high QC sharing

z2/resources/node_provision.tera.py, z2/src/chain.rs, z2/src/chain/node.rs
in this PR:
- feat: DEVOPS-1787 Remove rpc check on z2 deployer update
- feat: DEVOPS-1775 Adjust order of deployment operations to minimise node downtime when upgrading
=> feat: DEVOPS-1775 Adjust order of deployment operations to minimise node downtime when upgrading

infra/tf/main.tf
ID range: ["35.235.240.0/20"]
Port: TCP ["4202"]
target_tags = [var.chain_name]
=> feat: DEVOPS-1784 Allow IAP cidr access to TCP 4202 port

Cargo.lock, docker-compose.yaml, zilliqa/src/p2p_node.rs
Took a while to debug this issue - but I observed a lot of TCP retransmissions occurring in the present local docker network using wireshark, which hinted at an underlying networking issue.
Turns out that the nodes were communicating with each other over the gateway acting as a NAT-router. So, they were seeing the gateway IP/port as the remote IP/port. This is fine if it was used for responses (aka NAT) but would have problems if a client tried to initiate a connection to this ephemeral IP/port that isn't listening on the gateway.
This PR does two things:
- It makes node3 a dependency for all other nodes, as it is the bootstrap node.
- It manually adds the remote IP/ports to the list of known peers exploiting Identify.
- It manually adds the external IP/port (as observed from the remote …
=> Get local docker network running again.

z2/src/chain.rs, z2/src/chain/node.rs, zilliqa/src/cfg.rs
`Option::None` failed to parse into toml. Here we remove the key when its value is None.
=> fix: custom toml parsing of Option values

zilliqa/src/api/admin.rs, zilliqa/src/api/eth.rs
=> Fix block parameter for `admin_generateCheckpoint` and `eth_getBlockReceipts`

zilliqa/src/api/admin.rs, zilliqa/src/api/to_hex.rs, zilliqa/src/api/types/eth.rs, zilliqa/src/consensus.rs
This returns consensus-specific information that is useful for debugging the current status of a node.
Example:
```
$ xh post :4201 jsonrpc=2.0 id=1 method=admin_consensusInfo -b
{
"jsonrpc": "2.0",
"id": "1",
"result": {
"view": "0x1e",
"high_qc": {
"signature": "0xb82c814efbb00923e78f549e171932b5029d44f789b18d12fb877f01b6466c8658d62ddf9cb1dd1a44ffb3b7c2871bfd13e0ef1f79579f029e186990a94d20ea7526541b6b4d428b0bd3947c7f2d088744c85291d10dcfd05dc69f93991e198f",
"cosigned": "0xe000000000000000000000000000000000000000000000000000000000000000",
"view": "0x1c",
"block_hash": "0x3d0d192ef0235d632c4f115a9021245ac4047980422f12890e7f045157a746f2"
},
"milliseconds_since_last_view_change": 46,
"milliseconds_until_next_view_change": 4954
}
}
```
Closes #1753
=> Add `admin_consensusInfo` API

zilliqa/src/node.rs
PR #2042 added `NewView` broadcasting, but it didn't change anything because nodes ignored `NewView`s that were not sent via a direct request. In fact that PR made network recovery worse, since the leader would no longer see repeated `NewView`s. This PR just adds the handler for broadcasted `NewView`s.
=> Stop ignoring broadcasted `NewView`s

z2/resources/persistence_export.tera.sh, z2/src/chain/node.rs
Dedicated cron job installed in the checkpoint node to export the persistence to GCS.
Tests:
- No files in /data
- Files in /data/<chain>/checkpoints
=> feat: DEVOPS-1781 persistence export cron job for checkpoint node

z2/src/setup.rs, zilliqa/src/api/admin.rs, zilliqa/src/cfg.rs, zilliqa/src/consensus.rs, zilliqa/src/constants.rs, zilliqa/tests/it/main.rs, zq2-devnet.yaml
We now will always broadcast proposals when `milliseconds_remaining_of_block_time == 0`. This allows us to remove the further check on whether the exponential timeout has yet been reached when proposing (since the latter is always true if the former is true).
This means that if there are no consensus timeouts then we expect blocks to regularly be 1 seconds apart.
In `timeout()` Ive removed the check on `has_txns()` because transactions will be added to `early_proposal` when created and when received (if `early_proposal` exists). Whether there are txs in the mempool at this stage is irrelevant.
The `minimum_time_left_for_empty_block` variable is useful in a network in which a node is incentivised to add as many txs to their blocks as possible. Since fees are sunk in zq2 I have removed …
=> Simplify logic and variables involved in determining when to broadcast a Proposal

Cargo.lock, zilliqa/Cargo.toml, zilliqa/src/contracts/deposit_v4.sol
Removes `_stakerKeys` array. Perform check that staker can be updated by `msg.sender` explicitly.
Delegated_staking tests updated to test these changes [here](https://github.com/Zilliqa/delegated_staking/tree/deposit_v4).
Note that were merging into branch `deposit_v4`.
=> Remove _stakerKeys from Deposit contract

zilliqa/src/exec.rs
Added this piece of code to `scilla_create`
```rust
let mut input = String::new();
io::stdin()
.read_line(&mut input)
.expect("Failed to read line");
let input = input.trim();
let contract_address = zil_contract_address(from_addr, txn.nonce - 1);
println!("ADDR: {contract_address:?}, {}", current_block.number);
println!("Do you want to continue contract creation? y/n");
if input == "n" {
println!("no");
return Err(anyhow!("contract creation without init data"));
}
```
At first time I choose not to continue and fund the printed address. Then I redeploy and choose `y` to continue the deployment...
=> Fix balance of created Scilla contracts if they already have a non-zero balance

zilliqa/src/exec.rs
Reverts Zilliqa/zq2#2113
We should instead add this change with a flag in the fork configuration.
=> Revert "Fix balance of created Scilla contracts if they already have a non-zero balance"

zilliqa/src/api/types/zil.rs
`receipt.accepted==Some(false)` is now ignored, and if `receipt.success==true` the transaction is reported dispatched
@saeed-zil I noticed you already assigned yourself the associated issue after I pushed this, my bad.
Please feel free to reject it if's likely to cause a conflict with something you've already got in the works :)
=> Fix for issue where statuscode 255 was being returned even for succesful transactions

docs/api/eth/eth_gasPrice.doc.md
=> Corrected eth_gasPrice documentation where it mistakenly said eth_getGasPrice

.dockerignore
Because we didn't copy `Dockerfile` or `docker-compose.yaml` previously, `git describe` would mark our working directory as `-dirty` leading to a response like `v0.5.3-dirty` from `GetVersion`.
=> Fix all docker builds being marked as `-dirty`

z2/resources/chain-specs/zq2-prototestnet.toml, z2/src/chain.rs, zilliqa/src/cfg.rs, zilliqa/src/exec.rs, zilliqa/src/precompiles/scilla.rs
The correct behaviour is that EVM contracts should be treated as if they were EOAs in most non-exceptional cases. The exceptional cases are mentioned in #1610 and we'll make another change to this logic to deal with them later. This PR just adds the easy case and treats all EVM contracts as EOAs.
For now, we've just enabled this change in the proto-testnet, where we can easily update the nodes by the time the fork height is reached in ~1.5 days. There are further execution changes being worked on that we can release together in a single fork on the proto-mainnet.
=> Fix transactions where Scilla messages are sent to EVM contracts

zilliqa/src/db.rs
Trying out an idea. Not exactly sure how to interpret the Bencher Report but I believe that this small change has resulted in a modest improvement in performance.
```
process-empty/process-empty
time:   [4.7159 ms 4.7270 ms 4.7387 ms]
thrpt:  [211.03  elem/s 211.55  elem/s 212.05  elem/s]
change:
time:   [-12.425% -12.045% -11.635%] (p = 0.00 < 0.05)
thrpt:  [+13.167% +13.694% +14.187%]
Performance has improved.
Found 43 outliers among 500 measurements (8.60%)
17 (3.40%) high mild
26 (5.20%) high severe
Benchmarking produce-full/produce-full: Warming up for 3.0000 s
Warning: Unable to complete 20 samples in 120.0s. You may wish to increase target time to 159.2s, enable flat sampling, or reduce sample count to 10.
produce-full/produce-full
time:   [1.4192 s 1.7721 s 2.1411 s]
thrpt: …
```
=> Converted db.rs to use prepared statements.

z2/resources/chain-specs/zq2-protomainnet.toml, z2/resources/chain-specs/zq2-prototestnet.toml, z2/src/chain.rs, zilliqa/src/cfg.rs, zilliqa/src/exec.rs
Please let me know:
* if you have a better name for the config
* which config file(s) should I change accordingly?
=> feat: add option to adjust contract balance on deployment if already funded

.github/workflows/ci.yaml
Because `v5.0.5`  introduced a breaking change which causes our pipelines to fail.
`Error:   2:1  error  Compiler version ^0.8.20 does not satisfy the ^0.8.24 semver requirement  compiler-version`
=> chore: fix Solhint to v5.0.4

.github/workflows/base_benchmarks.yaml, .github/workflows/pr_benchmarks.yaml, Cargo.lock, zilliqa/Cargo.toml, zilliqa/benches/ERC20.sol, zilliqa/benches/it.rs, zilliqa/src/lib.rs, zilliqa/src/test_util.rs, zilliqa/src/time.rs
Previously we would generate pre-emptively generate 3.2 million transactions, just in case we ran enough iterations to need them. Instead, we use Criterion's `iter_batched` method to generate the transactions as they are needed. This ensures we don't generate more transactions than we need and that we don't consume loads of memory. The two downsides of this approach are:
* We don't generate transactions in parallel any more, but this doesn't seem to make much difference to the total benchmarking time now that we aren't over-generating transactions.
* The generated flamegraphs now include the transaction generation calls, but drilling down and ignoring them is only one keypress.
I've also renamed the benchmark from `produce-full` to `full-blocks-evm-transfers` since I think it better …
=> Add benchmarks for Scilla and ERC-20 transfers

zilliqa/src/contracts/deposit_v4.sol
- Set contract `VERSION=4`
- Fix Solidity version to `0.8.28`
- Remove double storage lookup of balance in `unstake()`. This saves 494 gas.
- Initialise `indices` in `getStakersData()` so that the function does not error
=> Fix deposit_v4 audit findings

zilliqa/src/api/mod.rs, zilliqa/src/node_launcher.rs
The default boundaries are too wide to be useful. Instead we use the standard boundaries for HTTP requests which will provide more useful results.
=> Fix boundaries for histogram metrics

infra/config_docker.toml, infra/config_rpc_disabled.toml, z2/src/chain.rs, zilliqa/src/cfg.rs, zilliqa/src/contracts/mod.rs, zilliqa/src/state.rs, zilliqa/tests/it/main.rs
- Introduce env var for setting `deposit_v4` contract upgrade block height
- Accounts for a [bug](https://github.com/Zilliqa/zq2/issues/2254) which overwrote the zero account's nonce value in proto nets
- Set upgrade height for devnet and prototestnet
=> feat: deposit_v4 config

zilliqa/src/scilla.rs, zilliqa/tests/it/zil.rs
It happened when there was a map containing maps as values, e.g `map<string, map<string, ...>>`. It triggered the assertion and led to node crash.
=> Fix crash while removing values from maps containing complex types

docker-compose.yaml, infra/config_docker.toml, z2/src/setup.rs, zilliqa/src/cfg.rs, zilliqa/src/p2p_node.rs
This adds support for multiple bootstrap peers. We use this in the local docker compose set up to ensure all nodes have at least one other node to talk to at startup, which they can use to find their own external address via autonat.
This also means we can remove the incorrect code where we always trust our observed external address once a single peer reports one. Instead, the external address candidates are passed to autonat and confirmed later.
The configuration change is backwards compatible, because we support either a single entry or a list of bootstrap peers now.
Fixes #2114.
=> Fix local docker compose runs

Cargo.lock, infra/config_rpc_disabled.toml, z2/Cargo.toml, z2/docs/join.md, z2/resources/chain-specs/zq2-devnet.toml, z2/resources/chain-specs/zq2-infratest.toml, z2/resources/chain-specs/zq2-perftest.toml, z2/resources/chain-specs/zq2-protomainnet.toml, z2/resources/chain-specs/zq2-prototestnet.toml, z2/resources/chain-specs/zq2-richard.toml, z2/resources/chain-specs/zq2-uccbtest.toml, z2/resources/config.tera.toml, z2/src/bin/z2.rs, z2/src/chain.rs, z2/src/chain/node.rs, z2/src/deployer.rs, z2/src/plumbing.rs, z2/src/validators.rs
We also made some miscellaneous improvements:
* Remove redundant fork configuration from rendered configuration files.
* Add `--out` parameter to `z2 deployer get-config-file` to output the rendered configuration to a file.
* Add `--otlp-endpoint` to `z2 join`.
Also this adds activation heights for the latest hardforks on protomainnet and prototestnet.
=> Update chain specification files

z2/src/chain/node.rs, z2/src/validators.rs
- Generating the otlp_collector_endpoint config in the nodes config.toml - beginning of the file (currently enforcing the otlp is part of all environments and configurations in GCP).
- z2 deployer get-config-file not affected, as the otlp_collector_endpoint is only added at the install/update process.
- Fix on the otlp_collector_endpoint var name for z2 join.
Tests with z2 deployer install:
```
z2 deployer ssh --select zq2-infratest.yaml -- cat /config.toml
Recompiling z2, please wait …
🦆 Running SSH command for zq2-infratest.yaml' ..
Using the project ID prj-d-zq2-devnet-c83bkpsd
Create the instance list for zq2-infratest
◇  Select target nodes
│  zq2-infratest-api-ase1-0-5155
│
Running SSH command on zq2-infratest nodes
🦆 Running the SSH command: 'cat /config.toml' ..
--- …
```
=> feat: DEVOPS-1867 otlp-collector endpoint generation in the node configs

zilliqa/benches/it.rs, zilliqa/src/db.rs
=> Issue #2242 load checkpoints as stream

docker-compose.yaml, infra/config_docker.toml, infra/opentelemetry/config_docker.toml, infra/opentelemetry/docker-compose.yaml
A few adjustments to make docker compose networks fully functional:
* use the addresses derived from 4 nodes'  private key as control address in the genesis deposits
* use a different IP and network name to avoid conflicts with the Zilstats agent running on the same machine
* use the devnet's chain id to make testing of deposit withdrawals possible within 5 minutes instead of 14 days
=> Adjust docker compose config files

z2/resources/node_provision.tera.py
Required to use the list of validators.
Tested in Grafana:
=> fix: DEVOPS-1850 single quotes in validation identities variable

z2/resources/node_provision.tera.py, z2/src/chain.rs, z2/src/chain/node.rs
- Adding log_level param in chains configuration (keeping it as a full string to allow more customizations, for example "zilliqa=info,opentelemetry=trace").
- Set log_level default to "zilliqa=trace" (as currently right now for all the chains).
- Removed not used validator_identities (this is managed now from Grafana).
- Only updating infratest to "zilliqa=info".
Tests (in infratest):
root@zq2-infratest-metrics-ase1-0-c06d:/home/pablo_zilliqa_com# docker exec -t c0bfebe18900 env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=zq2-infratest-metrics-ase1-0-c06d
TERM=xterm
RUST_LOG=zilliqa=info
RUST_BACKTRACE=1
HOME=/root
=> feat: DEVOPS-1870 log level parameter for zilliqa service

.gitignore, .solhint.json, infra/config_docker.toml, remappings.txt, z2/resources/chain-specs/zq2-devnet.toml, z2/resources/config.tera.toml, z2/src/chain.rs, z2/src/chain/node.rs, z2/src/setup.rs, zilliqa/src/cfg.rs, zilliqa/src/consensus.rs, zilliqa/src/contracts/README.md, zilliqa/src/contracts/deposit_v5.sol, zilliqa/src/contracts/mod.rs, zilliqa/src/contracts/tests/deposit.sol, zilliqa/src/state.rs, zilliqa/tests/it/main.rs
Adds `deposit_v5` with `withdrawalPeriod` configurable via `reinitialize()`.
Deposit tests are a work-in-progress but largely complete.
=> feat: set withdrawalPeriod at initialise of deposit_v5 and add deposit contract tests

z2/src/chain.rs, zilliqa/src/contracts/deposit_v5.sol, zilliqa/src/contracts/utils/deque_v2.sol
The old implementation was objectively broken and unnecessarily complicated. Instead, we just store elements in a `mapping(index => element)`.
=> Fix deque implementation in deposit contract

z2/src/chain/node.rs
Disable the API on our API nodes until https://github.com/Zilliqa/zq2/issues/2381 is resolved.
=> Disable `ots_contractCreator` API

zilliqa/src/exec.rs, zilliqa/src/scilla.rs
When applying EVM state deltas, we use the 'touched' flag to track if an account has been updated by an executed transaction.
We also add a similar flag to Scilla state deltas for the same purpose.
=> Avoid mutating state if accounts have not been updated

z2/resources/chain-specs/zq2-protomainnet.toml, z2/src/chain.rs
Running a sync revealed that the hardfork height was set too late. A scilla tx was executed in between `v0.6.0` being deployed and the hardfork at height `7966800`.
=> chore: update protomainnet scilla json ordering hardfork height

zilliqa/src/api/types/eth.rs, zilliqa/src/db.rs, zilliqa/src/node.rs, zilliqa/src/p2p_node.rs, zilliqa/src/sync.rs, zilliqa/tests/it/main.rs
1. Fixes the issue where, if an active-sync started on a losing branch of a fork, it may get stuck since all responses it receives are from the winning branch.
2. Fixes the issue where an active-sync might shoot past a checkpoint, by checking every single header downloaded against the blocks in the DB; and the first canonical block that hits the DB will turn the sync around.
3. Routes syncing blocks to lower-priority broadcast to avoid holding up the Requests queue with sync messages. Will hopefully reduce pressure on busy validators.
4. Minor fixes to syncing stats.
=> Sync at fork, and other fixes.

config-example.toml, config-single-node.toml, z2/resources/chain-specs/zq2-protomainnet.toml, z2/resources/chain-specs/zq2-prototestnet.toml, z2/src/chain.rs, zilliqa/benches/it.rs, zilliqa/src/cfg.rs, zilliqa/src/exec.rs, zilliqa/src/precompiles/scilla.rs, zilliqa/tests/it/contracts/ScillaInterop.sol, zilliqa/tests/it/zil.rs
When an interop. transaction is run, we need to be careful to keep track of state changes in both sides of the world.
This PR takes the approach of:
* Let `revm` keep track of EVM state changes as normal.
* When an interop call is made to the Scilla interpreter, we make sure any 'pending' changes from the EVM side are visible to the Scilla contract.
* When the Scilla call finishes, if any 'pending' EVM changes were modified further, we apply those changes to the EVM state journal before transferring control back to `revm`.
This ensures the state we read is consistent and that when we come to apply state delta updates, there is no overlap between the EVM and Scilla state maps.
=> Ensure state is correct in both EVM and Scilla environments

zilliqa/src/consensus.rs
See related issue for motivation.
This check feels incorrect - we should reject blocks whose view is less than our `finalised_view`, but a view less than head block's view is possible in fork scenarios. 
The check for less than `finalised_view` is performed already in `check_block()`.
=> fix: remove check for proposal view being more than head block's view

zilliqa/src/exec.rs, zilliqa/tests/it/staking.rs
In the old version, we would use a value of 5.5 million as the maximum possible gas that a transaction could use when estimating its actual usage. However, transactions can use more than this. The actual maximum is the block gas limit.
We instead use the minimum of the block gas limit and the maximum amount the caller could pay.
Fixes #2507, fixes #2508
=> Fix default gas for `eth_estimateGas`

zilliqa/src/consensus.rs, zilliqa/src/message.rs, zilliqa/src/node.rs, zilliqa/src/p2p_node.rs, zilliqa/src/sync.rs, zilliqa/tests/it/main.rs
This reverts commit 02890d0d76233199d1b27a6ae0da639c765ea6b7.
We suspect this may be causing the equivocation problems in proto-mainnet. We aren't completely sure it is the cause but @86667 and I are suspicious enough to think its worth trying.
=> Revert "Syncing leader must not propose. (#2450)"

zilliqa/src/sync.rs
This PR does 2 things:
1. Extracts a chain-segment from the cache-blocks during Phase-3, instead of blindly injecting everything, which can trigger forking issues not handled by `deal_with_fork()`.
2. Speeds-up Phase-2 by driving it even without Proposals.
It's currently deployed in `perftest`
=> Only inject newer blocks during Phase-3.

zilliqa/src/db.rs, zilliqa/src/sync.rs
This PR:
1. Moves the syncing metadata functionality from SQL/DB into in-memory structures; and
2. Minor change from Range to RangeInclusive that is semantically correct.
=> Move sync data from SQL to in-memory

zilliqa/src/consensus.rs, zilliqa/src/node.rs, zilliqa/tests/it/consensus.rs, zilliqa/tests/it/eth.rs, zilliqa/tests/it/main.rs, zilliqa/tests/it/persistence.rs, zilliqa/tests/it/staking.rs, zilliqa/tests/it/zil.rs
When a node is leader and receiving `NewView` messages it is possible that it sends two different `Proposal` messages. 
The reason this happens is that we do not execute our own proposals until they are delivered back to us via the broadcast mechanism, leaving an amount of time between broadcast and processing to re-gather repeated `NewView` messages and send off another proposal. 
I have opted to resolve this by executing our own proposals immediately after broadcasting them so that our `tip_info` is updated before any other work is done and thus any other messages for the view in which we proposed are ignored.
=> feat: handle own proposals immediately rather than wait for the broadcast

zilliqa/src/consensus.rs
By moving the oldness check and leader check earlier, we can skip unnecessary validation of the message if it will be ignored afterwards anyway.
=> Reject duplicate `NewView` messages faster

zilliqa/src/consensus.rs
Previously, when deleting unfinalized blocks on startup, we would update our high QC to ensure it was always pointing to a block we had stored. However, this causes restarted nodes to get far out-of-sync with the network with no easy way of recovering.
Instead, we let the high QC be dangling and handle the situations where it does not point to a block more gracefully:
* If we are building a `NewView`, we cannot work out the leader of the view so we unconditionally broadcast the `NewView` message.
* If we reach the next exponential timeout period, we cannot tell if we are in the current consnesus committee, so we unconditionally assume we are and send a `NewView`.
=> Gracefully handle situations where our high QC is dangling

zilliqa/src/consensus.rs, zilliqa/src/db.rs
If this flag is set in the database, we know we may have already voted for a proposal in our current view and thus can't send a `NewView` in the same view.
=> Prevent equivocation by storing `voted_in_view` flag

zilliqa/src/consensus.rs, zilliqa/src/db.rs
Previously, when a fork was detected, we would mark the previous block as 'non-canonical' and delete all transactions and receipts that were in that block.
This causes two problems:
* We are now no longer able to serve that block via P2P or the API, because we don't know which transactions it contains.
* If that block later becomes 'canonical' again and we need to re-execute it, we can't because we don't know which transactions it contains.
So instead we never delete values from `transactions` or `receipts`. We change the primary key of the `receipts` table from `tx_hash` to `(block_hash, tx_hash)`. This allows multiple entries to exist in `receipts` for the same transaction in different blocks and thus means we don't need to delete 'non-canonical' receipts.
=> Don't delete transaction receipts when a block is 'reverted'

Dockerfile, infra/run.sh
Query Scilla Server before starting Zilliqa node.
I spent too long trying to get this to work without `curl` and without horribly complex bash. If the `curl` install is not acceptable then happy to try again.
=> feat: do not start Zilliqa node if Scilla server is not reachable

Cargo.lock, zilliqa/src/db.rs
We should re-create the index with the same name as the original, so when the DB initialisation runs again it doesn't create a duplicate index.
=> Fix index name

z2/resources/node_provision.tera.py
We are getting OOM in the VMs and this it is affecting to the SSH, Logs and Metrics collection services, necessary to debug the issues that cause the high memory usage, among others. 
More details on the usage in the ticket: https://zilliqa-jira.atlassian.net/browse/DEVOPS-1944
We propose to set a memory limit in the container in order to avoid the other services in the VM to be affected. With this configuration, the Zilliqa process will still get out of memory but at least the common services in the VM will keep working.
The value is also a fixed one, as all the instance types currently have 8GB (n2-standard-2 and e2-standard-2).
We can eventually also explore other possible options as swap memory or oom-kill-disabled https://docs.docker.com/engine/containers/resource_constraints/
=> feat: DEVOPS-1944 zilliqa container hard memory limit to 6g

z2/src/setup.rs, zilliqa/src/cfg.rs, zilliqa/src/consensus.rs, zilliqa/src/p2p_node.rs, zilliqa/tests/it/main.rs
Configurable new view broadcast interval. Also sets Gossipsub's duplicate cache time to 1 hour to avoid re-broadcast loops between nodes which take >5 mins to process their message queues.
=> feat: set new view broadcast interval via config

zilliqa/benches/it.rs, zilliqa/src/consensus.rs, zilliqa/src/node.rs
A small bit of cleanup between return types from consensus layer
This is currently running in `zq2-devnet-validator-ase1-0-a6d2`.
=> refactor: Consistently return NetworkMessage back from consensus layer

z2/resources/node_provision.tera.py
Enable memory metrics by processes.
Tested in devnet.
https://monitoring.zilliqa.com/d/aee8cinu6kwlcc/zq2-uptime-status?orgId=1&from=now-1h&to=now&timezone=browser&var-project=prj-d-zq2-devnet-c83bkpsd&var-node=$__all
=> feat: DEVOPS-1946 memory metrics for processes monitoring

zilliqa/src/sync.rs
This was caused by the previous fix #2634 that tackled the issue of an empty segment, by:
1. Forcibly saving the marker; because there was a previous error that caused syncing to get stuck due to a missing marker 
2. Transition to Phase-3 if the marker was missing, which allows the sync to either finish up or restart.
This fix, only allows the saving of a marker for a non-empty segment; while preserving the state transition to Phase-3 if the marker was missing.
Currently deployed to all API nodes in `protomainnet`.
=> Fix sync metadata handling bug

zilliqa/src/consensus.rs
This code is called by the API to get pending block. It does not matter if the current state doesnt match that of the pending block's parent.
=> fix: remove useless and confusing warn log

zilliqa/src/consensus.rs
This PR fixes the issue we've been seeing in which nodes get stuck with 2 blocks both marked `is_canoncial = FALSE` and so cannot move forward: We check for loops slightly too early in the forking logic.
Also fixed is handling of self proposals which fail to finalise. Without this code I saw nodes attempt and fail to propose their bad blocks repeatedly, failing in a way which will never become successful.
One day I'll rewrite this forking code. I'm sure it can be made clearer but its not immediately obvious exactly how.
This code was deployed to prototestnet validators at 8pm on 14th April.
=> fix: Bug which checks for loops in forking code at the wrong time

zq2-devnet.yaml, zq2-infratest.yaml, zq2-mainnet.yaml, zq2-perftest.yaml, zq2-persistence.yaml, zq2-protomainnet.yaml, zq2-prototestnet.yaml, zq2-richard.yaml, zq2-testnet.yaml
Stats-agents promote to v0.0.3, which includes single line logs for stats-agent.
Tested OK:
2025-04-16 06:52 +00:00: [eth] =i= { id: 'zq2DevnetApiAse12B549', stats: { active: true, syncing: false, mining: false, peers: 9, gasPrice: '4761904800000', uptime: 100 } }
2025-04-16 06:52 +00:00: [eth] =i= { id: 'zq2DevnetApiAse12B549', stats: { active: true, syncing: false, mining: false, peers: 9, gasPrice: '4761904800000', uptime: 100 } }
2025-04-16 06:52 +00:00: [eth] =i= { id: 'zq2DevnetApiAse12B549', stats: { active: true, syncing: false, mining: false, peers: 9, gasPrice: '4761904800000', uptime: 100 } }
2025-04-16 06:52 +00:00: [eth] =i= { id: 'zq2DevnetApiAse12B549', stats: { active: true, syncing: false, mining: false, peers: 9, gasPrice: '4761904800000', uptime: 100 } }
Previous with …
=> feat: DEVOPS-1929 stats-agents promote to v0.0.3

infra/tf/checkpoints.tf, infra/tf/modules/node/main.tf, infra/tf/modules/node/outputs.tf, infra/tf/persistence.tf
To provide fine-grained access to resources we need to create a service account per node.
Tested and applied in infratest.
=> feat: DEVOPS-1986 service accounts per node

infra/tf/apps.tf, infra/tf/variables.tf, z2/resources/node_provision.tera.py, z2/src/chain.rs, z2/src/chain/node.rs
- Adding a enable_faucet variable in the chain definitions.
- Conditional deployment of faucet/spout resources.
- Separating the start/stop logic of the faucet from the apps.
- Tested with `z2 deployer install --select zq2-infratest.yaml`.
=> feat: DEVOPS-1991 not deploy faucet in mainnet

.github/workflows/ci.yaml, Dockerfile, z2/src/converter.rs, zilliqa-macros/src/test.rs
Includes 2 new commits:
https://github.com/Zilliqa/scilla/compare/a5a81f72...a886a135
The impactful one is https://github.com/Zilliqa/scilla/commit/a886a135f4ed570c4014ab10257a9506d1079ec6 which adds caching to the curl client and speeds up Scilla transactions significantly.
=> Update Scilla version

z2/resources/node_provision.tera.py, z2/src/chain/node.rs, zq2-infratest.yaml
Private key retrieved from inside the node instead of passing it as a variable in the node provisioner script.
Tested in infratest: 
90da4e38925c   asia-docker.pkg.dev/prj-p-devops-services-tvwmrf63/zilliqa-public/zq2:v0.8.0              "/run.sh 62831…"   About a minute ago   Up About a minute
=> feat: DEVOPS-1989 retrieve private key inside the node

z2/resources/node_provision.tera.py, z2/src/chain/node.rs
- Retrieve genesis key with gcloud from the node provisioner for spout app.
- Retrieve stats key with gcloud from the node provisioner for stats app.
Tested in infratest, commands used to compare the values:
cat /usr/local/bin/spout.sh
cat /usr/local/bin/stats_dashboard.sh
cat /usr/local/bin/stats_agents.sh
docker inspect --format='{{range .Config.Env}}{{println .}}{{end}}'
Stats showing on https://stats.zq2-infratest.zilstg.dev/
=> feat: DEVOPS-1989 retrieve genesis and stats key from inside the node

z2/src/docgen.rs, zilliqa/src/api/admin.rs, zilliqa/src/node.rs, zilliqa/src/node_launcher.rs, zilliqa/src/p2p_node.rs, zilliqa/tests/it/main.rs
Extends the `admin_getPeers()` RPC to return the totality of peers `swarm_peers`, not just the peers used for syncing `sync_peers`. The peers used for syncing is a subset as it only contains peers that are part of the topic, and are still good. So, it won't match the numbers in `net_peerCount` which will match `swarm_peers` returned in this PR.
If combined with #2730 the sync peers are the known peers in the topic. So, there will be no need to return a separate `topic_peers`.
=> Extend admin_getPeers() RPC

z2/resources/node_provision.tera.py
We need a way to associate a log and a container. This is a quick win option.
- record_log_file_path: Optional. If set to true, then the path to the specific file from which the log record was obtained appears in the output log entry as the value of the agent.googleapis.com/log_file_path label. When using a wildcard, only the path of the file from which the record was obtained is recorded.
=> feat: DEVOPS-1968 container id in log receiver

zilliqa/src/db.rs
[This PR](https://github.com/Zilliqa/zq2/pull/2588) stopped us from removing items from `receipts` table but did not remove the throw from the insert fn when an item already exists
=> fix: do not throw on attempted insert of existing item in receipts table

zilliqa/src/api/eth.rs, zilliqa/src/api/mod.rs, zilliqa/src/scilla.rs
@JamesHinshelwood I believe we have more sophisticated techniques for inspecting Scilla now. Let me know if these are still useful and I'll bring them back.
=> logging: Remove duplicate API call logging and remove Scilla state update logging

zilliqa/src/api/eth.rs, zilliqa/src/consensus.rs
Previously we got the block number by first getting the number, then getting the block, then discarding everything but the number
=> Improve performance of eth_blocknumber by reducing db queries

zilliqa/src/api/admin.rs, zilliqa/src/api/eth.rs, zilliqa/src/consensus.rs, zilliqa/src/node.rs
Some easy wins where `&mut self` was already unnecessary.
=> Reduce write locking of `Node`

zilliqa/src/api/eth.rs, zilliqa/src/api/types/filters.rs
This pushes the lock down to the inner filter map, meaning we can remove the top-level write locks.
I also simplified to cleanup implementation in filters. Now we only delete expired filters when we are attempting to add a new filter. This is the only time we might need to reclaim some memory.
=> Remove write lock when calling filter APIs

zilliqa/src/sync.rs
The current `admin_getPeers()` RPC only returns the list of unused sync-peers; missing out the ones that are in-flight.
=> admin_getPeers() should return the full list of sync-peers

zilliqa/src/p2p_node.rs
Although there are no more dropped publish messages, there are still a small number of dropped forwards. So, it might be useful to increase this slightly.
https://cloudlogging.app.goo.gl/nPKHvb3eMpt2DkAX9
=> increase gossipsub forward queue duration to 30s.

zilliqa/src/api/eth.rs, zilliqa/src/api/zilliqa.rs, zilliqa/src/consensus.rs, zilliqa/src/node.rs
This means we can make `handle_new_transaction` (and a few others) take a `&self`. Therefore, `eth_sendRawTransaction` can now be called concurrently.
=> Add locks around receipts cache and early proposal

zilliqa/src/node.rs, zilliqa/src/node_launcher.rs, zilliqa/src/p2p_node.rs, zilliqa/tests/it/consensus.rs, zilliqa/tests/it/main.rs
To avoid HOL-blocking issues on the request queue, reroute sync-related messages to broadcasts.
=> Reroute sync-requests to broadcast

zilliqa/src/p2p_node.rs
Backwards compatibility was for nodes running `< v0.9.1`.
=> feat: Remove resending of Validator GossipSub topic to general topic

zilliqa/src/consensus.rs
Missed from [this PR](https://github.com/Zilliqa/zq2/pull/2843) we do want to process our own `NewView` broadcast in case we are leader.
=> Handle own new view broadcast

zilliqa/src/consensus.rs
At some point the clone of `network_message_cache` was changed to a `take()`.
I may be suffering from Friday afternoon by not being able to find a clean way to borrow from `network_message_cache` to compare the view value before cloning. This works for now I'll come back to it on Monday to consider making it more elegant.
=> Do not take `network_message_cache` on first access

zilliqa/src/api/zilliqa.rs, zilliqa/tests/it/zil.rs
Fixes API inconsistency between ZQ1 and ZQ2 where GetSmartContractSubState would return an empty object `{}` instead of `null` when querying for:
- Non-existent variable names
- Non-existent map indices
ZQ1 behavior (expected): returns `null`
ZQ2 behavior (before fix): returns `{}`
ZQ2 behavior (after fix): returns `null` (matches ZQ1)
Changes:
- Modified get_smart_contract_sub_state() to check if result map is empty
- Return Value::Null when no matching state is found
- Added test case to verify the fix and prevent regression
This ensures API compatibility between ZQ1 and ZQ2 implementations.
=> Return null instead of {} for GetSmartContractSubState

z2/docs/deployer.md, z2/src/bin/z2.rs, z2/src/chain/config.rs, z2/src/chain/node.rs, z2/src/deployer.rs, z2/src/plumbing.rs
Removed references and commands.
```
z2 deployer --help
Recompiling z2, please wait …
Group of subcommands to deploy and configure a Zilliqa 2 network
Usage: z2 deployer [OPTIONS] <COMMAND>
Commands:
install               Install the network defined in the deployer config file
upgrade               Update the network defined in the deployer config file
get-config-file       Generate in output the validator config file to join the network
get-deposit-commands  Generate in output the commands to deposit stake amount to all the validators
deposit               Deposit stake amounts to the internal validators
deposit-top-up        Top up stake to the internal validators
unstake               Unstake funds of the internal validators
withdraw              Withdraw unstaked funds to the internal …
```
=> feat: DEVOPS-2060 remove deployer unused api command

z2/docs/deployer.md, z2/src/bin/z2.rs, z2/src/chain/node.rs, z2/src/deployer.rs, z2/src/plumbing.rs
`--no-restart` parameter in zq2 deployer restore
If specified, the service will not be restarted after the restore.
Tests:
`z2 deployer restore --no-restart zq2-infratest.yaml`
```
🦆 Restoring process for zq2-infratest.yaml ..
Using the project ID prj-d-zq2-devnet-c83bkpsd
Create the instance list for zq2-infratest
◇  Select target nodes
│  zq2-infratest-api-ase1-2
│
◇  Restoring the nodes data dir
│  ✔ zq2-infratest-api-ase1-2: Restore completed (service not restarted)
```
=> feat: DEVOPS-2093 no-restart option to avoid starting the service after zq2 restore

Cargo.lock, zilliqa-macros/src/test.rs, zilliqa/Cargo.toml, zilliqa/src/api/admin.rs, zilliqa/src/consensus.rs
By adding locks around the vote storage in `Consensus`, we are now able to call it non-exclusively. The locks are actually internal to the `Dashmap`s but the effect is the same.
=> Make `Consensus::vote` take `&self`

zilliqa/src/consensus.rs, zilliqa/src/node.rs
- Update taking of a write lock until its required
- Take a single write lock per tx batch rather than taking a fresh one for each tx in the batch
- Fix a bug in which an `early_proposal` was cleared without its transactions being added back to the pool
- Some `consensus.rs` docs
=> A couple transaction pool write lock efficiency gains and a fix for clearing `early_proposal` without adding txs back to pool

zilliqa/src/message.rs, zilliqa/src/p2p_node.rs
To avoid cross-pollution e.g. Proposals sent as requests, being received and processed. The node will only receive and then process expected message flows.
=> Make message routing, stricter - dropping unexpected messages, early.

zilliqa/src/api/zilliqa.rs, zilliqa/src/node.rs, zilliqa/tests/it/zil.rs
This fixes the remaining few places where we would query data from the latest block instead of the finalized block.
=> Always expose the finalized block in Zilliqa APIs

zilliqa/src/sync.rs
There is a case where the sync response could be larger than the batch size. This handles that case.
=> Handle large sync response

z2/resources/chain-specs/zq2-mainnet.toml
It was only mainnet keeping the old version
=> Downgrade deposit to v5

infra/ansible/group_vars/network_zq2_devnet/all.yml, infra/ansible/group_vars/network_zq2_infratest/all.yml, infra/ansible/group_vars/network_zq2_mainnet/all.yml, infra/ansible/group_vars/network_zq2_protomainnet/all.yml, infra/ansible/group_vars/network_zq2_prototestnet/all.yml, infra/ansible/group_vars/network_zq2_testnet/all.yml, infra/ansible/playbooks/templates/spout.sh.j2, infra/ansible/playbooks/templates/stats_agent.sh.j2
Possibility of alternative dns for spout and otterscan services. Already applied.
=> feat: DEVOPS-2116 alternative dns option for spout and otterscan services

infra/tf/api.tf, infra/tf/apps.tf, infra/tf/checkpoints.tf
Using the standard (and clean) approach provided by GCP. 
https://cloud.google.com/load-balancing/docs/https/setting-up-reg-http-https-redirect
Same logic as in GKE apps, having 2 url maps.
Applied and tested in and infratest and devnet. Once approved, will be promoted to testnet and mainnet.
=> feat: DEVOPS-2118 force http to https redirect in all endpoints

zilliqa/src/sync.rs
This PR does 2 things:
1. Send empty response for active-sync request of ZQ1 blocks.
2. Prevent the startup of nodes without a checkpoint, on testnet/mainnet.
So, it makes it clear that a testnet/mainnet node MUST be restored from a checkpoint. It cannot start active syncing from nothing.
This will break misconfigured 0.11 nodes. So, this will have to go out with 0.12 - and people are informed of the breaking change. Otherwise, they will just get stuck syncing - there is no other error for 0.11 nodes.
We should deploy this to validator nodes first, which won't break the network since the API nodes can still service 0.11 calls, until such time that we are comfortable to switch to 0.12 fully.
=> Block active-sync of ZQ1 blocks

z2/src/converter.rs, zilliqa/src/consensus.rs, zilliqa/src/db.rs, zilliqa/src/sync.rs, zilliqa/src/transaction.rs
- actual verification is skipped on retrieval
- Should fix error when retrieving some ZQ1 transactions
- I haven't actually changed what's stored in the db, that could come later if we like this approach
Let me know if this doesn't work for some reason - it just seemed nicer and more consistent than adding one-off ignoring verification
=> Moved db wrapper to accepting and returning verified transactions

zilliqa/src/consensus.rs, zilliqa/src/p2p_node.rs, zilliqa/src/sync.rs
Currently deployed in `devnet`.
It addresses some potential issues with spamming - details in issue #2990 
1. It does a rudimentary sanity check on gossipsub and punishes any node that broadcasts spam.
2. It reduces the maximum range of a sync request to a reasonable number to mitigate sync spam.
3. It prunes stale buffered votes, which it did not do previously, to mitigate vote spam.
=> Added some spamming mitigations

zilliqa/Cargo.toml, zilliqa/src/api/eth.rs, zilliqa/src/api/trace.rs, zilliqa/src/exec.rs, zilliqa/src/node.rs
ZQ1 used SputnikVM (London) which did not have EIP3607 support. ZQ2 uses REVM (Shanghai) which has EIP3607 turned on by default.
This PR selectively disables EIP3607 for calls from `eth_call` and `eth_estimateGas` to emulate the previous ZQ1 behaviour.
=> Disable EIP-3607, for ZQ1 compatibility.

infra/tf/api.tf, infra/tf/variables.tf
- allow ip ranges for security policy.
- allow custom rules for security policy.
Configurable from z.yaml:
```
api:
allow_ip_ranges:
zq2_mainnet_apps_ase1_0:
priority: 900
description: "ZQ2 mainnet apps node"
src_ip_ranges: ["xxxxxxxxxx"]
kucoin:
priority: 901
description: "KuCoin"
src_ip_ranges: ["xxxxxxxxxx"]
straitx:
priority: 902
description: "StraitX"
src_ip_ranges: ["xxxxxxxxxx"]
bitkub:
priority: 903
description: "Bitkub"
src_ip_ranges: ["xxxxxxxxxx"]
allow_custom_rules:
viewblock_bypass:
priority: 801
description: "Bypass rate limit by header key for ViewBlock"
expression: "xxxxxxxxxxxxx"
```
=> feat: DEVOPS-2125 api whitelisted ips for security policy

zilliqa/src/api/txpool.rs, zilliqa/src/api/types/txpool.rs, zilliqa/tests/it/txpool.rs
If pending or queued are fully empty they're ignored too
=> Empty txpool content entries now ignored

infra/ansible/playbooks/templates/healthcheck.py.j2
Currently the condition to calculate the next checkpoint is it not considering that the time from the production to the upload can also increase. For that reason we have some micro alerts.
One solution is to extend the treshhold, but since we don't want to use a fixed number, we can just re-add the difference that took from produce to upload the checkpoint (for mainnet is 700 blocks, which will remove the alert).
=> feat: DEVOPS-2047 extending the blocks for gcs checkpoint failure condition

zilliqa/src/api/mod.rs
This should make it easier to debug panics that happen during API calls in future.
Also logs the stack trace
=> Return stack trace when API calls panic

infra/ansible/playbooks/templates/ethereum_metrics_exporter.sh.j2
Constant memory usage is:
namedprocess_namegroup_memory_bytes(virtual) -> 1.19GiB 
namedprocess_namegroup_memory_bytes(resident) -> 44.5 MiB
Docker Memory Limit Should Be Based on RSS
Setting it to a limit of 512m, to avoid affecting other services, and keeping it high, because the current usage of the instance is 15% approx. In case of OOM, the container will restart and will go back to the expected constant usage.
=> feat: DEVOPS-2184 memory limit for ethereum-metrics-exporter

zilliqa/src/db.rs
The symptom was that syncing got stuck due to failures in verifying the block hash:
```
2025-07-31T05:23:58.429227Z  INFO zilliqa::sync: 794: sync::MultiBlockResponse : received range=484846..=484906 from=12D3KooWFPfLCWc3dTMM4FFBFKQGACjPEKG5juyQW9CzJdUQ7v8e
2025-07-31T05:23:58.430149Z  INFO zilliqa::consensus: 724: handling block proposal 9e1f472ec87c66684a3c25c30d0ea1db8ad32ed997bc1657950426cb9c3a5bab block_view=484865 block_number=484846 txns=148
2025-07-31T05:23:58.430234Z  WARN zilliqa::consensus: 759: invalid block proposal received! e=invalid hash 6c67581aca1076a953447d64972654f2de3ecd4787c869fe625fe15c7dd28276 != 9e1f472ec87c66684a3c25c30d0ea1db8ad32ed997bc1657950426cb9c3a5bab
2025-07-31T05:23:58.430341Z  INFO zilliqa::sync: 949: sync::MissingBlocks : requesting …
```
=> Fix for invalid block hash errors during sync

zilliqa/src/consensus.rs, zq2-devnet.yaml, zq2-infratest.yaml, zq2-mainnet.yaml, zq2-testnet.yaml
There seems to be a toctou-like issue in some instances introduced by #3070.
This PR bypasses the failing check during sync, as it no longer makes sense to check that since the transaction has already been executed in other nodes prior.
=> Bypass txn validation during sync recovery

zilliqa/src/pool.rs
First of all, I added `delete_transactions` functions to TransactionPoolCore and TransactionsAccount
Then, I added the transaction expiry mechanism itself It's fairly approximate but should be good enough.
The mechanism is:
1. `hash_to_txn_map` is augmented to record the time when transactions were added to the pool
2. When the first transaction is added to the pool, `oldest_insertion_time` is set
3. When `oldest_insertion_time` is older than `expiry_time_clearout_threshold` (currently 48h), a clearout is initiated on the next add_txn()
4. During the clearout:
5. All transactions older than `pool_expiry_time_minimum` (currently 24h) are deleted
6. `oldest_insertion_time` is updated to the new oldest transaction
The end result should be that every 24h, we clear out everything older than …
=> Added an expiry mechanism to the transaction pool

zilliqa/src/api/txpool.rs, zilliqa/src/consensus.rs, zilliqa/src/node.rs, zilliqa/src/node_launcher.rs
There were some unnecessary `write()` locks being taken, some that are triggered periodically e.g. `txpool_status()` rpc calls from the stats agent. Turn them all into `read()` locks to minimise any possible blocking, which may slow down RPC calls.
=> Convert unnecessary write() locks to read() locks

z2/resources/chain-specs/zq2-devnet.toml, z2/resources/chain-specs/zq2-mainnet.toml, z2/resources/chain-specs/zq2-testnet.toml, z2/src/chain.rs, zilliqa/src/cfg.rs, zilliqa/src/exec.rs, zilliqa/tests/it/zil.rs
Gas returned is gas_used, not gas_left. Also there's some formatting applied to toml files (by running `z2/update-chain-specs.sh`).
=> Fixing failed eoa transfers via zil api

Cargo.lock, zilliqa/Cargo.toml, zilliqa/src/db.rs, zilliqa/src/node.rs, zilliqa/src/node_launcher.rs
This PR does 2 main things:
1. Replace the `Mutex<Connection>` with a connection pool, which moves locking to the underlying db layer. This allows for concurrent reads and writes, due to the use of `WAL` in the db. The size of the pool is dynamically capped at twice the number of worker threads.
2. Replace the `Mutex<LruCache>` with a `RwLock<LruCache>` to allow for concurrent reads. A major performance issues is reading a large amount of state. Allowing concurrent reads hopes to alleviate some of that. The trade-off is that the cache behaviour becomes FIFO-like rather than LRU-like.
This change is minor - as it does not change the underlying database. It is currently running on half the `devnet` nodes for testing. No significant adverse impact observed.
*The hope is that this change will …
=> Improve concurrent DB access

zilliqa/src/constants.rs, zilliqa/src/db.rs, zilliqa/src/sync.rs
This PR provides a fix for a off-by-one error, when running passive-sync from a checkpoint. The parent block in the checkpoint file is stored without any of its transactions, and passive-syncing starts from its parent (i.e. grand-parent) block. As a result, there is a possibility of missing transactions/receipts for the parent block.
This issue was missed in earlier testing because it turns out that most checkpoint blocks are empty blocks. Manual checking (`eth_getBlockByNumber`) shows that less than a handful of blocks in `mainnet` are impacted by this issue. Only nodes that have passive-synced from non-empty checkpoint parents are impacted.
This fix does two things:
1. Alter passive-sync to sync from the lowest block, inclusive (rather than exclusive, previously); and
2. Introduce a …
=> Fix passive-sync off-by-one error

zilliqa/src/consensus.rs
This PR improves state-sync by removing the DashSet, which stores all past state changes. This DashSet is unnecessary as we only need to detect a state change, which only requires a difference between the current state, and previous state. So, we only store the `last_hash` instead of the full history of changes. 
This is done to avoid possible (not actual) OOM issues.
=> Fix possible state-sync issue

zilliqa/src/consensus.rs, zilliqa/src/state.rs
Replacing another Mutex with a RwLock. Probably simple enough to cherry-pick into `v0.18.1`, if we want to.
=> Removed Mutex from State::account.

zilliqa/src/db.rs, zilliqa/src/sync.rs
This PR restores the previous behaviour where a syncing error will be triggered, instead of being silent, when a block fails to be inserted. With an error, the syncing process stops whereas the silent behaviour results in failing to sync forever.
In the specific case of a passive-sync, there is no real reason for an error since it involves a historical block. Any underlying SQL errors, such as connectivity issues, will be caught in the subsequent inserts.
=> Restore previous error behaviour

Cargo.lock, z2/Cargo.toml, z2/src/docgen.rs, zilliqa/Cargo.toml, zilliqa/src/node.rs, zilliqa/src/node_launcher.rs, zilliqa/src/p2p_node.rs, zilliqa/tests/it/main.rs
This PR is to improve code hygiene. Replace use of `unsafe` code with the ArcSwap crate.
=> Replace `unsafe` code with `ArcSwap` crate

zilliqa/src/sync.rs
I will merge this once tests pass - since it is a self-contained change.
=> Set sled cache_capacity to 1MB for temporary databases

z2/resources/chain-specs/zq2-testnet.toml, z2/src/chain.rs
Will merge this once it passes with the node in `testnet`
=> Update fork height for Scilla precompile failure to 9494740

zilliqa/src/crypto.rs, zilliqa/src/sync.rs
A previous fix https://github.com/Zilliqa/zq2/pull/3145 attempted to solve the issue of checkpoint parents missing transactions, by simply re-syncing the lowest block, at all times - forcibly syncing any checkpoint parent.
This causes an issue with a rare case, where only 1 block is able to fit into a response payload (either due to size or time). In such a case, it is possible for the passive-sync to get stuck repeatedly syncing only the lowest block. Re-syncing the lowest block is needed only for the checkpoint parent, which is stored without any associated transactions.
=> Adjust passive-sync logic to handle blocks with missing transactions

infra/ansible/playbooks/install_rocksdb_tools.yml, infra/ansible/playbooks/node_provision.yml, infra/ansible/playbooks/upgrade_ubuntu.yml
Ensure the installation of the rocksdb-tools only if Ubuntu 24.04 is the distribution version.
Tests:
- Installed in Ubuntu 24.04 node:
```
TASK [Ensure rocksdb-tools is installed] ***************************************************
changed: [zq2-devnet-persistence-ase1-0] => {"cache_update_time": 1759482170, "cache_updated": true, "changed": true,
```
- Not installed in Apps node:
```
PLAY [Install required packages] ***********************************************************
skipping: no hosts matched
```
- Not installed in Ubuntu 24.04 or higher:
```
TASK [Ensure rocksdb-tools is installed] ***************************************************
skipping: [zq2-testnet-persistence-ase1-0] => {"changed": false, "false_condition": "ansible_distribution_version is version(\"24.04\", '>=')", …
```
=> feat: DEVOPS-2354 rocksdb-tools installation

infra/ansible/playbooks/upgrade_ubuntu.yml
Python scripts installations are required after the Ubuntu upgrade, otherwise venv libraries are not properly installed.
Tested successfully with the Testnet network.
=> feat: DEVOPS-39 ubuntu upgrade post installations
