- zilliqa/src/api/zilliqa.rs
Internally we represent balances with 18 decimal places. However, the Zilliqa API expects 12 decimal places, so we need to scale and truncate the amount.
I figured it made more sense to truncate rather than round, because a lower bound for an account's balance is more useful if you're trying to work out how much they could spend. Happy to discuss if others disagree though.
> Fix balance scaling for Zilliqa `GetBalance` API

- scripts/js_test.sh
I think the author deleted their repo?
> remove ansi from js test

- zilliqa/src/message.rs
> Display for QC

- zilliqa/src/consensus.rs
> cleaner QC construction

- .github/workflows/ci.yaml
After discussions on test timeouts, thought I would add this to see what people think. It seems to work well (first commit intentional test timeout for reference).
> add a ci level timeout for rust tests

- zilliqa/src/exec.rs
Move the existing check to the start of `apply_transaction`, since there's no need to do any EVM processing if we already know the nonce is wrong.
> Fail transaction execution early if there's a nonce mismatch

- zilliqa/src/message.rs
enable bls, but make sure to also sign against the view
> Enable bls, but also sign on the view

- .github/workflows/ci.yaml
- .github/workflows/deny.yaml
this PR in concert with enabling the merge queue in the branch protection will allow to leverage on merge queue to auto merge the changes each PR.
> feat: DEVOPS-1072 Enabling merge queues in zq2 repo

- zilliqa-macros/src/test.rs
as discussed in a prev PR - it simply panics at the end if it took too long all in all.
> time bound the tests

- zilliqa/src/p2p_node.rs
* Dial the configured bootstrap node straight away to speed up subsequent requests.
* Run the Kademlia bootstrap process every 5 minutes to ensure we discover new nodes periodically. Also run an early bootstrap if a point-to-point message fails because we sent it to a peer that we didn't know the address of.
* Ignore advertised loopback addresses
> Fix peer discovery

- zilliqa/src/p2p_node.rs
At debug level, we log all libp2p swarm events. As it stands, lots of useful events such as errors are lost by our `_ => {}` branch.
In future, we should consider handling more of of these cases explicitly and log `error!`s.
> Log swarm events

- evm_scilla_js_tests/hardhat.config.ts
- evm_scilla_js_tests/helpers/SignersHelper.ts
- evm_scilla_js_tests/tasks/InitSigners.ts
Added files `InitSigners.ts` and `SignersHelpers.ts` from the zq1 code base to make perf work and the rest are small tweaks.
> Make perf tool work on zilliqa2 code base

- README.md
- zilliqa/src/api/mod.rs
- zilliqa/src/api/types/mod.rs
- zilliqa/src/api/types/zil.rs
- zilliqa/src/api/zil.rs
- zilliqa/src/node.rs
As mentioned in #79, we have further work to do later to fill some of these fields.
> Implement `GetTxBlock{,Verbose}`

- zilliqa/src/api/types/zil.rs
> Fix more field names for GetBlockchainInfo

- evm_scilla_js_tests/test/Errorneous.ts
- evm_scilla_js_tests/test/Transfer.ts
It didn't wait for the proper receipt before querying affected nonce and balance.
> Fixing test

- zilliqa/src/consensus.rs
Previously this was disabled because it didn't work. This is because we reconstructed the QCs with the signer's committee index rather than their public key.
Fixes #706.
> Verify signatures of aggregate QCs

- z2/src/converter.rs
- zilliqa/src/api/types/eth.rs
- zilliqa/src/api/types/ots.rs
- zilliqa/src/consensus.rs
- zilliqa/src/message.rs
- zilliqa/src/transaction.rs
I chose to add the value to block headers, rather than calculate it on the fly. Feel free to discuss if you think the denormalisation is a bad idea.
I also removed a (IMO) misguided `Display` impl for blocks.
Resolves #978.
> Add `gasUsed` to block headers

- zilliqa/src/consensus.rs
Previously, we would check the sanity but just log a warning if it was not within our allowed skew. Now we correctly reject blocks with non-plausible timestamps.
I also changed our code to reject blocks it recieves with a view of 0, rather than silently accepting them.
> Enforce sanity of block proposal timestamps

- z2/src/bin/z2.rs
- z2/src/collector.rs
- z2/src/components.rs
- z2/src/docs.rs
- z2/src/lib.rs
- z2/src/mitmweb.rs
- z2/src/otel.rs
- z2/src/otterscan.rs
- z2/src/plumbing.rs
- z2/src/setup.rs
- z2/src/spout.rs
- z2/src/zq2.rs
- zilliqa/src/cfg.rs
(feat) Build and provide generated documentation with z2
(feat) z2 can now enumerate its requirements
(fix) Fix up config generation sufficient for z2 to work again
closes #997
> #997 Docs in z2 

- docs/api/zilliqa/gettransaction.doc.md
- zilliqa/src/api/types/zil.rs
- zilliqa/src/api/zil.rs
- zilliqa/src/pool.rs
- zilliqa/src/transaction.rs
> Implement `GetTransaction` for non-Zilliqa transactions

- README.md
- docs/api/eth/eth_accounts.doc.md
- docs/api/eth/eth_blocknumber.doc.md
- docs/api/eth/eth_call.doc.md
- docs/api/eth/eth_chainId.doc.md
- docs/api/eth/eth_estimateGas.doc.md
- docs/api/eth/eth_getBalance.doc.md
- docs/api/zilliqa/getbalance.doc.md
- docs/testing.md
- z2/resources/api_notes.tera.md
- z2/resources/supported_apis.tera.md
- z2/src/bin/z2.rs
- zilliqa/src/api/eth.rs
- zilliqa/tests/it/eth.rs
- zilliqa/tests/it/main.rs
Relates to, but doesn't complete, #1014
> First tranche of eth_ API documentation

- zilliqa/Cargo.toml
- zilliqa/src/db.rs
This was useful to me when debugging some other changes.
> Log executed SQL statements

- Cargo.lock
- z2/Cargo.toml
- zilliqa/Cargo.toml
- zilliqa/src/exec.rs
- zilliqa/src/precompiles.rs
Update the following dependencies:
* `alloy-consensus` - git dependency -> `0.1.2`
* `alloy-eips` - git dependency -> `0.1.2`
* `alloy-rpc-types` - git dependency -> `0.1.2`
* `alloy-rpc-types-trace` - git dependency -> `0.1.2`
* `revm` - `9.0.0` -> `10.0.0`
* `revm-inspectors` - git dependency -> `0.1.2`
and everything downstream of them in the dependency tree.
> Update `revm` and `alloy` dependencies

- zilliqa/src/consensus.rs
- zilliqa/src/pool.rs
PR #1156 fixed this in one place, but missed this one.
> Fix empty pool condition when deciding whether to propose the next block

- zilliqa/src/consensus.rs
As requested by: https://github.com/Zilliqa/zq2/issues/977
> Remove redundant time_since_last_block

- Cargo.lock
- zilliqa/Cargo.toml
- zilliqa/src/api/mod.rs
* `opentelemetry`: 0.23.0 -> 0.24.0
* `opentelemetry_sdk`: 0.21.2 -> 0.24.1
* `opentelemetry_otlp`: 0.14.0 -> 0.17.0
> Update opentelemetry dependencies

- Cargo.lock
- z2/Cargo.toml
- zilliqa/Cargo.toml
- zilliqa/src/crypto.rs
Description in the linked ticket.
> Migrate bls crates to blsful

- zilliqa/src/crypto.rs
- zilliqa/src/db.rs
- zilliqa/src/message.rs
* Fixes https://github.com/Zilliqa/zq2/issues/1330
> Make checkpoint config option idempotent

- CHANGELOG.md
- zilliqa/src/consensus.rs
- zilliqa/src/node.rs
- zilliqa/src/transaction.rs
Fixes: https://github.com/Zilliqa/zq2/issues/1352
> Execute txns with current block rather than their parent

- z2/resources/checkpoints.tera.sh
- the latest checkpoint is copied to the root folder of the bucket
- the files have the extension `.block` added
- retention policy lowered to 30
- all the checkpoints a part the current, are moved to the folder `/previous`
- removed checkpoint "latest"
> feat: DEVOPS-1533 update checkpoint cronjob

- z2/resources/start_validator.tera.sh
Updated the documentation in this PR -https://github.com/Zilliqa/dev-portal/pull/36/files
> Fix launch script to add checkpoint configuration

- CHANGELOG.md
Also, add missing entry for #1398.
> Bump changelog for v0.2.0

- CHANGELOG.md
- zilliqa/src/consensus.rs
> Avoid voting for a new view if we aren't in the commitee

- z2/src/docgen.rs
(i believe) changes to API structure in dev docs
> (feat) zq2 half of the documentation changes.

- z2/resources/supported_apis.tera.md
> (fix) Update zq2 documentation

- z2/resources/supported_apis.tera.md
> (fix) Remove spurious line

- Cargo.lock
- z2/Cargo.toml
- z2/docs/deployer.md
- z2/src/bin/z2.rs
- z2/src/chain.rs
- z2/src/chain/config.rs
- z2/src/chain/instance.rs
- z2/src/chain/node.rs
- z2/src/deployer.rs
- z2/src/lib.rs
- z2/src/plumbing.rs
- zq2-infratest.yaml
in this PR:
- DEVOPS-1559 z2 deployer upgrade should not upgrade the node in parallel
- DEVOPS-1552 Install/update single instances
> feat: DEVOPS-1559 z2 deployer upgrade should not upgrade the node in parallel

- README.md
- z2/README.md
- z2/docs/README.md
- z2/docs/join.md
- z2/docs/local-network.md
- Fixed some docs and moved them around slightly
- Removed duplicates
> docs: remove duplicate z2 instructions plus a little clean up

- CHANGELOG.md
- zilliqa/src/api/types/zil.rs
- zilliqa/src/api/zil.rs
- zilliqa/tests/it/zil.rs
Add GetTransactionsForTxBlockEx API, along with associated type, and test
The test is fairly minimal, since this is fairly simple code
A future PR might include a test setup with a more developed example network
> Add GetTransactionsForTxBlockEx API

- CHANGELOG.md
- docs/checkpoints.md
- infra/config.toml
- zilliqa/src/consensus.rs
- zilliqa/src/db.rs
- zilliqa/src/message.rs
- zilliqa/src/p2p_node.rs
- zilliqa/tests/it/main.rs
- zilliqa/tests/it/persistence.rs
> Fix checkpoints: State at checkpoint should contain current block data as well as parent block data

- CHANGELOG.md
- zilliqa/src/api/zil.rs
- zilliqa/tests/it/zil.rs
Simple implementation, the calculation is the same as in `get_blockchain_info`
> Add `GetNumDSBlocks` API

- infra/tf/main.tf
Adding the support for UDP for the p2p 3333 port.
> feat: DEVOPS-1594 udp firewall port for p2p

- z2/docs/deployer.md
- z2/resources/node_provision.tera.py
- z2/src/bin/z2.rs
- z2/src/chain/node.rs
- z2/src/deployer.rs
- z2/src/plumbing.rs
- zq2-devnet.yaml
- zq2-infratest.yaml
in this PR:
- implement nodes data dir backup and restore
- update documentation
- update devnet and infratest versions to latest
- improve logging format
- add timeout to z2 deployer rpc calls
> feat: DEVOPS-1586 implement z2 deployer backup and restore

- zilliqa/src/api/zil.rs
> (fix) Check for 0 nonce so as to avoid a panic!() later

- CHANGELOG.md
- evm_scilla_js_tests/test/rpc/eth_getCode.ts
- zilliqa/src/api/eth.rs
> Return `0x` from `eth_getCode` for EOAs

- zilliqa/src/consensus.rs
- zilliqa/src/crypto.rs
- zilliqa/src/exec.rs
This simplifies our code and surprisingly also improves performance:
```
process-blocks/process-blocks
time:   [7.4686 ms 7.4895 ms 7.5099 ms]
thrpt:  [133.16  elem/s 133.52  elem/s 133.89  elem/s]
change:
time:   [-4.3650% -4.0025% -3.6431%] (p = 0.00 < 0.05)
thrpt:  [+3.7809% +4.1694% +4.5642%]
Performance has improved.
```
> Remove `NodePublicKeyRaw`

- CHANGELOG.md
- docs/api/zilliqa/getrecenttransactions.doc.md
- zilliqa/src/api/types/zil.rs
- zilliqa/src/api/zil.rs
- zilliqa/tests/it/zil.rs
- plus two tests
- First commit was named "Add GetNumDSBlocks API.", but that was a typo, this is really for GetRecentTransactions
> Add `GetRecentTransactions` API.

- zilliqa/src/api/zil.rs
- zilliqa/tests/it/zil.rs
- Closes #1594 
- Also refactored get_txn_bodies_for_tx_block_ex in order to share code and avoid repetition
> Implement GetTxnBodiesForTxBlock API

- zilliqa/src/api/zil.rs
- zilliqa/tests/it/zil.rs
Addresses bug mentioned in #1590 by @chetan-zilliqa 
Closes #1593 which tracks this bug specifically
> Changed DSBlockListing to take an int argument rather than a string

- zilliqa/src/api/zil.rs
- zilliqa/src/block_store.rs
- zilliqa/src/db.rs
- zilliqa/tests/it/zil.rs
> Implement GetNumTransactions

- zilliqa/src/consensus.rs
We were cloning `self.state` lower down in the stack than necessary after `early_proposal_...` functions's behavior has changed slightly. These changes narrow cloning down to only:
- `early_proposal_apply_transcations()` 
- `early_proposal_finish_at()`
The previous `self.state` root is then restored before those fns return.  This results in far cleaner code which is much less error-prone.
> Reduce state cloning 

- Cargo.lock
- zilliqa/Cargo.toml
- zilliqa/src/api/zil.rs
- zilliqa/tests/it/zil.rs
- Plus tests
- serde_json updated to latest version (v1.0.132) in order to gain access to support u128
- Closes #1549
- Closes #1550
> Implement GetTotalCoinSupply and GetTotalCoinSupplyAsInt

- z2/resources/chain-specs/zq2-devnet.toml
- z2/resources/chain-specs/zq2-prototestnet.toml
- z2/resources/chain-specs/zq2-uccbtest.toml
- z2/resources/config.tera.toml
... so that the genesis account contains a useful amount of zil.
> (fix) Adjust network genesis account contents 

- zilliqa/src/api/zil.rs
This fixes #1691 and https://github.com/Zilliqa/gozilliqa-sdk/issues/122
> Add contract_address in response if code is present

- zilliqa/src/consensus.rs
After dropping and re-syncing it is possible that the current leader receives votes and adds them to their `buffer_votes` because they are not yet caught up to the view which the votes apply to. 
In this circumstance there is a bug which causes `create_next_block_on_timeout` to be set to `false` after having just been set to `true`, and thus the proposal is never sent.
> fix: Do not stop proposal of early_proposal when buffered votes are counted

- zilliqa/src/api/zil.rs
- zilliqa/tests/it/zil.rs
Plus added a test for GetSmartContractInit
Fixes #1701
> Fix for GetSmartContractInit returning different error messages

- z2/src/bin/z2.rs
- z2/src/utils.rs
.. minor, but useful (to me, at least!)
> (feat) Allow the user to specify a checkpoint when joining an existing network

- zilliqa/Cargo.toml
- zilliqa/src/p2p_node.rs
It seems to interact weirdly with autonat in real networks.
> Remove mDNS

- docs/api/zilliqa/getprevdifficulty.doc.md
- docs/api/zilliqa/getprevdsdifficulty.doc.md
- zilliqa/src/api/zil.rs
- zilliqa/tests/it/zil.rs
- Difficulty is no longer relevant in ZQ2 so these are placeholders
- Plus documentation changes
- Plus tests
- Closes #1599
- Closes #1598
> Implement GetPrevDifficulty and GetPrevDSDifficulty

- scripts/zilliqa_api_comparator/.gitignore
- scripts/zilliqa_api_comparator/README.md
- Corrected a reference to the python script name in the readme
- Added a Python .gitignore (mainly to ignore .venv)
These are super unimportant changes, but I've made a PR to not forget them.
> Small tweaks to comparator

- zilliqa/tests/it/zil.rs
Just some additional tests for API behaviours based on the docs - they all pass, I'm just adding them for completeness and so nobody else needs to
> Additional API tests

- zilliqa/src/api/eth.rs
As per @bzawisto comments in #1882
> fixed gas limit coming from config

- zilliqa/src/api/zil.rs
- Added error for account contract queries
- Added error for address does not exist
- Closes #1800
> Fixed error return types for GetSmartContracts

- Cargo.lock
- zilliqa/Cargo.toml
- zilliqa/benches/it.rs
- zilliqa/src/pool.rs
- zilliqa/src/time.rs
Plus a few changes to our benchmarks to make it easy to produce flamegraphs from them.
> Add benchmark for production of full blocks

- z2/resources/chain-specs/zq2-richard.toml
- z2/src/chain.rs
.. so that you can join nodes to the zq2-richard network.
> (fix) Add configuration file for zq2-richard

- zilliqa/src/consensus.rs
Benchmark with this PR + #1942 
```
produce-full/produce-full
time:   [1.6839 s 1.7362 s 1.7660 s]
thrpt:  [0.5662  elem/s 0.5760  elem/s 0.5938  elem/s]
change:
time:   [-55.243% -52.889% -50.495%] (p = 0.00 < 0.05)
thrpt:  [+102.00% +112.26% +123.43%]
Performance has improved.
```
Before:
After:
> Batch transaction inserts when building a block

- zilliqa/src/contracts/deposit_v1.sol
- zilliqa/src/contracts/deposit_v2.sol
- zilliqa/src/contracts/mod.rs
- zilliqa/src/contracts/utils/deque.sol
Updated deposit contracts to comply with linting rules as specified in  https://github.com/Zilliqa/delegated_staking/tree/solidity_linting
> Deposit contracts linting

- zilliqa/src/contracts/deposit_v1.sol
- zilliqa/src/contracts/deposit_v2.sol
- zilliqa/src/contracts/mod.rs
- zilliqa/src/exec.rs
- zilliqa/src/state.rs
- zilliqa/tests/it/consensus.rs
- zilliqa/tests/it/staking.rs
Clone of https://github.com/Zilliqa/zq2/pull/1948
```
curl -X POST   -H "Content-Type: application/json"   --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x00000000005A494C4445504F53495450524F5859", "latest"],"id":1}' http://localhost:4201/
{"jsonrpc":"2.0","id":1,"result":"0x2116545850052128000000"}
```
> Fix genesis deposit balances in Solidity.

- Cargo.lock
- infra/tf/locals.tf
- z2/Cargo.toml
- z2/docs/deployer.md
- z2/docs/join.md
- z2/resources/chain-specs/zq2-protomainnet.toml
- z2/resources/chain-specs/zq2-prototestnet.toml
- z2/resources/start_node.tera.sh
- z2/src/bin/z2.rs
- z2/src/chain.rs
- z2/src/chain/config.rs
- z2/src/chain/instance.rs
- z2/src/chain/node.rs
- z2/src/deployer.rs
- z2/src/plumbing.rs
- z2/src/validators.rs
- zq2-devnet.yaml
- zq2-infratest.yaml
- zq2-perftest.yaml
- zq2-protomainnet.yaml
- zq2-prototestnet.yaml
- zq2-richard.yaml
- zq2-uccbtest.yaml
in this PR:
- update z2 deployer documentation
- remove project_id from chain config
- rename container arg in z2 join with image-tag
- enable node selection in z2 deployer rpc
> feat: various optimization and bug fix

- z2/resources/chain-specs/zq2-devnet.toml
- z2/resources/chain-specs/zq2-protomainnet.toml
- z2/resources/chain-specs/zq2-prototestnet.toml
- z2/resources/config.tera.toml
- z2/src/chain.rs
- z2/src/chain/node.rs
If no forks are configured, we shouldn't include the configuration key at all.
> Fix fork configuration for devnet

- z2/src/address.rs
- z2/src/bin/z2.rs
- z2/src/chain/node.rs
- z2/src/deployer.rs
- z2/src/validators.rs
- zilliqa/src/bin/convert-key.rs
- zilliqa/src/consensus.rs
- zilliqa/src/crypto.rs
- zilliqa/src/db.rs
- zilliqa/src/message.rs
- zilliqa/tests/it/staking.rs
A bit of code cleanup. No change to behavior expected.
> Bls signature and z2 Validator type cleanup

- zilliqa/src/block_store.rs
- zilliqa/src/range_map.rs
Most calls to `with_range` just add a single element to the end of the largest existing range. Previously, this required inserting an extra 1-wide range at the end of the list, then iterating through the list again to merge the two final ranges.
Instead, we just add an explicit check for this case (and the case) where the new range is strictly greater than the largest existing range.
There are certainly more efficient ways to solve the general case of `with_range` but this fixes the immediate problem with block syncing speed on my machine, so I would propose merging it anyway.
> Optimise common cases in `RangeMap::with_range`

- zilliqa/src/contracts/deposit_v4.sol
Creates a new file `deposit_v4` with changes:
- https://github.com/Zilliqa/zq2/pull/2105
- https://github.com/Zilliqa/zq2/pull/2110
> feat: deposit_v4

- zilliqa/src/consensus.rs
Mainly making view and block number logging more clear
> fix: minor logging improvements

- zilliqa/src/api/eth.rs
- zilliqa/src/api/trace.rs
Closes #2217 
trace_block, trace_filter and trace_transaction aren't included to avoid a merge conflict with #2205
> Added nicer error messages for unimplemented methods

- zilliqa/src/consensus.rs
Explanation here - https://github.com/Zilliqa/zq2/issues/2309#issuecomment-2648571799
> fix: do not attempt to fetch all blocks in AggQC from storage

- z2/resources/node_provision.tera.py
- zilliqa/src/api/types/eth.rs
- zilliqa/src/node.rs
- zilliqa/src/p2p_node.rs
- zilliqa/src/sync.rs
These are just some small fixes to syncing e.g. more debugging/tracing, some minor bugs, separated out from #2354, which would require more investigation.
> Misc sync fixes

- zilliqa/src/precompiles/scilla.rs
Calling transitions with 'contract' parameter types (e.g. `ByStr20 with contract end`) is now supported.
This also adds some additional trace-level logging to the precompile implementation.
> Support complex Scilla address types in `scilla_call` precompile

- docs/api/zilliqa/gettxblock.doc.md
- docs/api/zilliqa/gettxblockverbose.doc.md
> Document rewards==0 return in gettxblock and gettxblockverbose apis

- Cargo.lock
- zilliqa/Cargo.toml
> Revert "build(deps): bump bincode from 1.3.3 to 2.0.0"

- zilliqa/src/consensus.rs
We also fix our high QC to ensure it always points to a block we have stored.
> Delete unfinalized blocks on startup

- zilliqa/src/consensus.rs
We trigger a block request probe upon seeing a high qc for a block we dont have to a single peer. If the peer chosen does not have the block either, then the next `NewView` will trigger the same code to probe the next peer.
> feat: trigger sync when we see a high qc for a block we do not have

- zilliqa/src/sync.rs
This PR does 2 things:
1. Rate-limits `sync_from_probe()` calls to under 1-probe/min; and
2. Caches probe responses, to avoid rebuilding the Proposal each time.
> Reduce probe spam

- z2/src/converter.rs
- z2/src/zq1/persistence.rs
Scilla receipts shouldn't be transformed into evm ones during conversion.
> ZQ1 scilla receipt are incorrectly converted

- zilliqa/src/sync.rs
While there is no evidence in the logs that something weird has happened (other than in #2622 / #2626), this PR introduces a backup check, to fail any stale requests that are stuck 'in-flight' for more than 30-seconds.
In the case of a false positive:
- In phase 1, it would resend the request to another peer while any belated response to the original request gets dropped.
- In phase 2, it would switch to retry phase 1 on that segment while any belated response to the original request gets dropped.
It will also log any stale requests when it happens, for further monitoring.
In addition, another bug (stuck in Phase 2) that might have occurred is when the code for Phase 1 turnaround got changed in #2623. As a result, there is now a rare exception where it is possible for there to be zero …
> Backup check for sync stuck in-flight

- zilliqa/src/consensus.rs
When a block is reverted we continue to collect votes for it. That is correct, though we should not count a supermajority as a trigger for blindly proposing whatever we have in our `early_proposal` in case it's the forked block which has the votes.
> fix: Check votes apply to block before proposal

- z2/src/chain.rs
- z2/src/chain/node.rs
Genesis deposits amount value included in the chain configurations and references in the node setup. Tested in infratest config.toml.
> feat: DEVOPS-1995 genesis deposits amount by chain

- zilliqa/src/api/types/eth.rs
- zilliqa/tests/it/eth.rs
> Correct sha_3_uncles return and add test

- zilliqa/src/consensus.rs
My previous PR moved the leader validation earlier, but that means we no longer take the high QC from received `NewView`s if we aren't the view's leader. This moves the check after the high QC update.
We still keep the old-ness check before the leader check to mitigate some extra work.
> Update high QC from `NewView` messages

- z2/resources/node_provision.tera.py
- z2/src/chain.rs
- z2/src/chain/instance.rs
- z2/src/chain/node.rs
- z2/src/deployer.rs
Enabling KMS decrypt and encrypt options by chain
> feat: DEVOPS-2015 kms enabled by chain

- zilliqa/src/consensus.rs
- zilliqa/src/message.rs
- zilliqa/src/node.rs
- zilliqa/src/p2p_node.rs
- zilliqa/tests/it/main.rs
And Broadcast `NewView`s on that topic.
For backwards compatibility we'll have to send to both topics until the version after these changes are included.
> feat: Create separate GossipSub topic for Validators

- zilliqa/src/api/admin.rs
- zilliqa/src/api/types/admin.rs
- zilliqa/src/api/types/mod.rs
- zilliqa/src/consensus.rs
Achieves some of #2726 but doesn't yet calculate supermajority
> Added `votes` and `buffered_votes` fields to admin_votesReceived

- .github/workflows/ci.yaml
- Dockerfile
- z2/src/converter.rs
- zilliqa/src/test_util.rs
This version supports heap profiling
> Update Scilla version

- infra/tf/kms.tf
- infra/tf/variables.tf
- z2/src/chain/instance.rs
- z2/src/chain/node.rs
- z2/src/kms.rs
- If required, executing the kms commands in a node, avoiding the local permissions restriction.
- Group access option to devnet non-prod keys.
> feat: DEVOPS-2033 executing kms commands in the node

- zilliqa/src/consensus.rs
Need @86667 to weigh in on this PR.
> Resend vote on timeout

- zilliqa/src/api/admin.rs
- zilliqa/src/api/types/admin.rs
- zilliqa/tests/it/admin.rs
Problem was that BTreeMap doesn't like to serialize with non-numeric keys So I changed to vecs
Closes #2780
> Fix admin_votesReceived bug

- zilliqa/src/p2p_node.rs
This never felt correct to me. It feels like something which was implemented as a hacky fix for a less mature code base.
> Do not process own broadcasts

- zilliqa/src/cfg.rs
- zilliqa/src/p2p_node.rs
Both DHTs currently running in `v0.9.3` in both proto nets.
This code will go into a `v0.10.0`
> feat: remove duplicate kademlia

- zilliqa/src/node_launcher.rs
If any of the transactions fail for whatever reason, the node would be terminated. This avoids that.
> Gracefully handle broadcast transactions.

- zilliqa/src/consensus.rs
- zilliqa/src/pool.rs
- zilliqa/src/transaction.rs
Moved over from https://github.com/Zilliqa/zq2/pull/2896
> Size limit transactions

- infra/tf/checkpoints.tf
- infra/tf/variables.tf
Alternative domain support for checkpoints.
> feat: DEVOPS-2115 checkpoints alternative domain support

- zilliqa/src/pool.rs
- Specifically, this occured only if the account in question had no pending transactions
- unwrap panic fixed, general behaviour changed to just warnings for executing non-pending transactions
> Fix for a panic generated when executing a non-pending transaction

- zilliqa/src/api/zilliqa.rs
- zilliqa/src/transaction.rs
- zilliqa/tests/it/zil.rs
- Adjusted amount down by 10^6, and subtracted null address balance
- Updated test
- Extra methods for ZilAmount
> Fixed total coin supply APIs

- README.md
- infra/scripts/zurl.sh
- scripts/setenv
Tool to curl to internal GCP instances via IAP.
To be enabled by source `scripts/setenv`
> feat: DEVOPS-2092 zurl tool

- docker-compose.yaml
- infra/config_docker.toml
If you start the local docker network and try to use the faucet to send yourself some funds, it will fail. This fixes things.
> local docker network was broken.

- zilliqa/src/consensus.rs
- zilliqa/src/constants.rs
- zilliqa/src/p2p_node.rs
- zilliqa/src/sync.rs
- zilliqa/tests/it/main.rs
Standardised some constants, so that they're same across different parts of the program.
> fix failing benchmark

- z2/src/plumbing.rs
- z2/src/setup.rs
- zilliqa/benches/it.rs
- zilliqa/src/cfg.rs
- zilliqa/src/db.rs
- zilliqa/src/node.rs
- zilliqa/src/pool.rs
- zilliqa/src/state.rs
- zilliqa/tests/it/main.rs
since this is a very small config change, i think it's fine to get into `v0.18.0`.
> added node.db config to tune database.

- zilliqa/src/consensus.rs
This PR unifies the pending/early proposal generation.
1. Multiple calls to `eth_getBlockByNumber("pending")` (and other similar calls) within the same view, will: return the existing early-proposal; or generate it lazily, once. This results in a slight-speedup if there are multiple calls within a view; but a slight slowdown if it is only called once per view.
2. If the node is a validator, the same block is proposed. This improves consistency in that the call will return the *actual* pending block.
> Simplify early/pending proposal

- z2/resources/config.tera.toml
I'll merge this once the new checkpoint is generated.
> Reduce cache sizes to prevent OOM

- zilliqa/src/db.rs
Since this is a very simple change; with no-material impact; I will directly merge it in once tests pass.
> Make vacuuming, a TODO.

- zilliqa/src/db.rs
When a `SELECT` is performed in SQLite with the `IN` filter, the results are returned in db-order, not in filter-order. This PR fixes the case when db-order is not the same as receipt-order.
> Ensure receipt-order matches transactions
